### ISSUE TITLE
openai version > 1.0.0 is not supported

### ISSUE THREAD

**Issue by YarinDay** [DataDog/dd-trace-py#7581] opened 2023-11-14 09:31 UTC
Hey there!

Related to this issue:
[issue](https://github.com/DataDog/dd-trace-py/issues/7494)

Wanted to know if there is any updates on when it will become available since it's pretty urgent for us.
Thank you and have a great day!

**Comment by Yun-Kim** [comment] 2023-11-14 14:51
Hi @YarinDay, thanks for reaching out!

#7513 was just merged which adds support for `openai>=1.0`. This will be released in ddtrace 2.2.0, hopefully sometime this week.

Closing as this is a duplicate of #7494 and resolved.

**Closed by Yun-Kim** 2023-11-14 14:51 UTC
