### ISSUE TITLE
import deadlock when setting gunicorn logger class

### ISSUE THREAD

**Issue by jpcope** [DataDog/dd-trace-py#827] opened 2019-02-13 21:31 UTC
Image from problem statement:

![image](https://user-images.githubusercontent.com/9321688/52745399-8ab88000-2fa4-11e9-8830-e00bc8b3b855.png)

RUNTIME:
1. flask
1. gunicorn
1. gevent
1. structlog

I wrote up a Simplest Repeatable Test Form for this one using docker so you can see exactly how we are making the runtime.

https://github.com/jpcope/srft/tree/issue/ddtrace-logging-import-bug

If I remove the ddtrace-run statement it initializes without issue.
It I move the logger class outside of the `app` directory it initializes and listens without issue.

---

The import statement of the logging class never returns under these conditions. Repeating the import procedure in a custom script will reveal this is the case:

pipenv run python

```python
import ddtrace # comment me out and get a yay!
ddtrace.patch_all() # comment me out and get a yay!

from gevent import monkey
monkey.patch_all()

print('welp...')
from app.logging import StructuredLogger
print('yay')
```

yay never prints.

**Comment by jpcope** [comment] 2019-02-13 22:59
This additional information was requested from a zendesk email:
> 1. Please send us a “flare” (copy of your agent’s logs and configs) by following the corresponding instructions from the following documentation per your operating system and infrastructure. Please ensure to follow the initial steps requesting that you enable DEBUG level logging, and that a time frame passes in which traces should be produced, prior to running your flare command. When you run the flare command you’ll append your ticket number of [REDACTED_CASE_ID].

```bash
# install the agent inside the container after exec'ing into it
DD_API_KEY=[REDACTED_API_KEY] bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"
datadog-agent flare '[REDACTED_CASE_ID]'
```

output:
```text
Please enter your email:
[REDACTED_EMAIL]
Asking the agent to build the flare archive.
The agent was unable to make the flare. (is it running?)
Initiating flare locally.
Error: Alibaba HostAliases: unable to query metadata endpoint: Get http://100.100.100.200/latest/meta-data/instance-id: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: Azure HostAliases: unable to query metadata endpoint: Get http://169.254.169.254/metadata/instance/compute/vmId?api-version=2017-04-02&format=text: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: temporary failure in criutil, will retry later: no cri_socket_path was set
Error: temporary failure in clusterAgentClient, will retry later: cannot get a cluster agent endpoint for kubernetes service DATADOG_CLUSTER_AGENT, env DATADOG_CLUSTER_AGENT_SERVICE_HOST is empty
Error: Containerd init error: temporary failure in containerdutil, will retry later: failed to dial "/var/run/containerd/containerd.sock": context deadline exceeded
Error: temporary failure in dockerutil, will retry later: could not determine docker server API version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: returned hostname "" with error: temporary failure in dockerutil, will retry later: try delay not elapsed yet
Error: unable to fetch EC2 API, Get http://169.254.169.254/latest/meta-data/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: Get http://169.254.170.2/v2/metadata: dial tcp 169.254.170.2:80: connect: connection refused
Error: temporary failure in ecsutil, will retry later: try delay not elapsed yet
Error: unable to retrieve hostname from GCE: Get http://169.254.169.254/computeMetadata/v1/instance/hostname: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error: temporary failure in kubeutil, will retry later: unable to get hostname from docker, please set the kubernetes_kubelet_host option: temporary failure in dockerutil, will retry later: try delay not elapsed yet
Error: temporary failure in apiserver, will retry later: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Error: Could not collect go routine stack traces: Get http://127.0.0.1:5000/debug/pprof/goroutine?debug=2: dial tcp 127.0.0.1:5000: connect: connection refused
/tmp/datadog-agent-2019-02-13-22-55-50.zip is going to be uploaded to Datadog
Are you sure you want to upload a flare? [Y/N]
Y
Your logs were successfully uploaded. For future reference, your internal case id is [REDACTED_CASE_ID]
```

> 2. Please also provide the version numbers for the tracing client, language, and any frameworks you are using.

Exact package versions can be found in the file: https://github.com/jpcope/srft/blob/issue/ddtrace-logging-import-bug/Pipfile.lock
You may be more familiar with the general pip format from "pipenv run pip freeze"

```text
Click==7.0
ddtrace==0.20.4
Flask==1.0.2
gevent==1.4.0
greenlet==0.4.15
gunicorn==19.9.0
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
msgpack-python==0.5.6
python-json-logger==0.1.10
six==1.12.0
structlog==19.1.0
Werkzeug==0.14.1
wrapt==1.11.1
```

> 3. Please share the configurations you’ve used inside your application to enable any automatic instrumentation. If you have implemented any manual instrumentation, please share an example of that code as well. Any example code that will help our team replicate the issue would be helpful and can be shared in a private gist.

Please see the SRFT: https://github.com/jpcope/srft/tree/issue/ddtrace-logging-import-bug

**Comment by brettlangdon** [comment] 2019-02-15 22:57
@jpcope thank you for reporting this issue.

I started digging into it, and this is an interesting issue for sure.

I narrowed it down to being a deadlock in `importlib.import_module` when you circular import `from app import app` within `app/routes.py`.

With your example app, I can reproduce without `gunicorn` at all via: `ddtrace-run python wsgi.py`.

I have also confirmed that the problem does go away if you remove `ddtrace-run`, but the problem also goes away when you remove the `gevent` monkey patching.

I found this open issue for `gevent` which sounds very similar: https://github.com/gevent/gevent/issues/1345

I am stuck on exactly how/why `ddtrace-run` would be causing this issue. I would have guessed if we were patching `gevent` then I could see why that would be an issue, but in the example you shared, we are not.

I know `gevent` does some import hi-jacking, and we do as well, maybe something isn't playing as nicely when they are together.

This is a tricky one, I will have to spend a little more time with it.

**Comment by brettlangdon** [comment] 2019-02-15 22:59
Also note, we haven't run into this issue with customers using `gevent` before, but maybe there is something magical about the circular import which is raising the issue.

**Comment by jpcope** [comment] 2019-02-17 03:07
Thanks @brettlangdon !

I agree, the circular import is most likely the main reason that a deadlock happens. I am not aware if is or is not an acceptable practice in python and I am overall very surprised that the 3.6.5 import routines are not screaming that a circular import happened and is not supported. It could very well end up being a bug in python; an edge case they do not support but should still be able to catch and error.

It is an interesting problem, thanks for continuing to dive head-first into it!

**Comment by brettlangdon** [comment] 2019-02-18 14:35
Yeah, circular imports do "work", but usually frowned upon because there are weird edge cases you can hit. You basically need to understand and document the behavior since if someone decides to move an import to the top of a file or something, then everything can fall apart.

For Flask setups I usually recommend going with the [Application factory pattern](http://flask.pocoo.org/docs/0.12/patterns/appfactories/). It is pretty common pattern and the nice thing about it is you can control when the application gets bootstrapped.

This behavior is still weird and it worth investigating a bit, we will have to try and schedule some time to dive into further it since it feels nasty.

**Comment by majorgreys** [comment] 2019-04-30 15:47
@jpcope Thank you for sharing the repo. It made diagnosing the problem a whole lot easier.

I found that your issue is resolved if you upgrade `ddtrace` to `>=0.21.0`. I've included the diff of my working directory with your repo. I avoided using the provided `Pipfile.lock` in the `Dockerfile` script (as well as changed the starting image since `jessie` was throwing up repo errors).

Can you please give this a go and tell us if it resolves your issues in using your `app.logging.StructuredLogger`?

We will be digging deeper into understanding why `0.21.0` resolves this problem.

``` patch
diff --git a/Dockerfile b/Dockerfile
index 665267f..7639088 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM python:3.6.5-slim-jessie
+FROM python:3.6.5-slim

 ARG S6_VERSION=v1.21.4.0
 ENV S6_VERSION=$S6_VERSION
@@ -36,7 +36,7 @@ RUN export DEBIAN_FRONTEND=noninteractive && \
 # configure WORKDIR
 WORKDIR /opt/service

-COPY ./Pipfile* ./
+COPY ./Pipfile ./
 RUN pipenv run python -m pip install pip==18.0 \
     && ( test ! -f Pipfile.lock || pipenv sync ) \
     && ( test -f Pipfile.lock || pipenv install )
diff --git a/Pipfile b/Pipfile
index 7f4012d..0d78874 100644
--- a/Pipfile
+++ b/Pipfile
@@ -6,12 +6,12 @@ name = "pypi"
 [dev-packages]

 [packages]
-ddtrace = "*"
+ddtrace = "==0.21.0"
 gevent = "*"
 flask = "*"
 gunicorn = "*"
 structlog = "*"
-python-json-logger = "*"
+python-json-logger = "==0.1.10"

 [requires]
 python_version = "3.6"
```

**Comment by brettlangdon** [comment] 2019-09-03 20:20
@jpcope were you able to try upgrading the tracer version, has your issue been resolved?

I am going to close this issue for now due to age, please feel free to re-open it if you are still having trouble.

**Closed by brettlangdon** 2019-09-03 20:20 UTC

**Comment by jpcope** [comment] 2019-09-06 15:27
Thank you, issue is definitely resolved:  https://github.com/jpcope/srft/pull/1

I hope a test exists such that we do not get a regression in the future :-)
