### ISSUE TITLE
Datadog exception jwt.exceptions.ExpiredSignatureError: : "Signature has expired"

### ISSUE THREAD

**Issue by sylvainmouquet** [DataDog/dd-trace-py#3688] opened 2022-05-06 17:58 UTC
Hello,

We have gone this error yesterday : 
```
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/futures/threading.py", line 43, in _wrap_execution
    return fn(*args, **kwargs)
jwt.exceptions.ExpiredSignatureError: Signature has expired
```

How to fix this type of error? it concernes the interaction with datadog ?
We use the ddtrace version : `version = '0.57.4'`

**Comment by Kyle-Verhoog** [comment] 2022-05-06 18:10
Hi @sylvainmouquet, it looks like `ddtrace` is just in the stack trace here but isn't the cause of the exception.

**Comment by Kyle-Verhoog** [comment] 2022-05-06 21:23
Going to close the issue as it appears as though this isn't `ddtrace`-related. If you feel it is we can re-open @sylvainmouquet 🙂

**Closed by Kyle-Verhoog** 2022-05-06 21:23 UTC

**Comment by sylvainmouquet** [comment] 2022-05-06 23:20
Ok thanks for the response I will continue to search the origin
