### ISSUE TITLE
[Bug] Infinite waiting state in dd profiling

### ISSUE THREAD

**Issue by KannappanChida** [DataDog/dd-trace-py#6533] opened 2023-07-31 14:31 UTC
### Summary of problem

Infinite waiting state occurred in dd profiling

### Which version of dd-trace-py are you using?

1.12.1

### Which version of pip are you using?

23.1.2

### Stack Trace

    File "/conda/envs/conda_robot_framework/lib/python3.8/threading.py", line 890, in _bootstrap
      self._bootstrap_inner()
    File "/conda/envs/conda_robot_framework/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/conda/envs/conda_robot_framework/lib/python3.8/site-packages/ddtrace/internal/periodic.py", line 55, in run
      while not self.quit.wait(self.interval):
    File "/conda/envs/conda_robot_framework/lib/python3.8/threading.py", line 558, in wait
      signaled = self._cond.wait(timeout)
    File "/conda/envs/conda_robot_framework/lib/python3.8/threading.py", line 311, in wait
      self._acquire_restore(saved_state)
    File "/conda/envs/conda_robot_framework/lib/python3.8/threading.py", line 259, in _acquire_restore
      self._lock.acquire()           # Ignore saved state
    File "/conda/envs/conda_robot_framework/lib/python3.8/site-packages/ddtrace/profiling/collector/_lock.py", line 121, in acquire
      self._self_recorder.push_event(event)
    File "/conda/envs/conda_robot_framework/lib/python3.8/site-packages/ddtrace/profiling/recorder.py", line 63, in push_event
      return self.push_events([event])
    File "/conda/envs/conda_robot_framework/lib/python3.8/site-packages/ddtrace/profiling/recorder.py", line 75, in push_events
      with self._events_lock:

### What is the result that you expected?

successful completion of dd-profiling without any infinite waiting state.

**Comment by P403n1x87** [comment] 2023-07-31 14:34
Hi @KannappanChida. This seems to be a duplicate of #6308. Would you be able to upgrade to a latest version of ddtrace, where the fix is already available?

**Closed** 2023-08-07 17:31 UTC
Labels: Profiling
