### ISSUE TITLE
Time-Series data doesn't show up when an environment is specified

### ISSUE THREAD

**Issue by ffoxdd** [DataDog/dd-trace-py#186] opened 2017-02-17 16:30 UTC
When I configure traces to have the "env" tag set to anything other than None, time series data doesn't show up in the web frontend.

This happens if I set the environment like this:
`tracer.set_tags({"env": "DEVELOPMENT"})`

or like this:
`tracer.current_span().set_tag("env", "DEVELOPMENT")`

<img width="1142" alt="screen shot 2017-02-17 at 11 25 30 am" src="https://cloud.githubusercontent.com/assets/518723/23073662/4927abca-f504-11e6-86a0-2d2010678586.png">

**Comment by LeoCavaille** [comment] 2017-02-21 10:09
Hi @ffoxdd, thanks for the bug report.
I think this is likely a normalization issue, your env tag being upper case and not complying with the Datadog tag charset.

From [documentation](https://help.datadoghq.com/hc/en-us/articles/204312749-Getting-started-with-tags):
> Tags must start with a letter, and after that may contain alphanumerics, underscores, minuses, colons, periods and slashes. Other characters will get converted to underscores. Tags can be up to 200 characters long and support unicode. Tags will be converted to lowercase.

I believe this is not a bug in the python client but in the agent where I opened a bug to fix that in the next release (we'll workaround it in the meantime) https://github.com/DataDog/datadog-trace-agent/issues/232.

**Comment by galdor** [comment] 2017-02-21 14:13
Fixed in DataDog/datadog-trace-agent#232.

**Closed by galdor** 2017-02-21 14:13 UTC
