### ISSUE TITLE
Python Snowflake Driver Team says You're Importing OpenTelemetry wrong

### ISSUE THREAD

**Issue by lattwood** [DataDog/dd-trace-py#11407] opened 2024-11-14 14:45 UTC
Python Snowflake Driver Team says you're including `opentelemetry-api` wrong.

I think they're the ones that are wrong, by building opentelemetry into their connector, instead of getting their instrumentation landed here: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation

and in an ideal world, in this repo as well.

Would ya'll mind sorting this out?

https://github.com/snowflakedb/snowflake-connector-python/issues/2084

Thanks!

**Comment by bogdandrutu** [comment] 2024-11-14 16:06
@lattwood I don't they Snowflake is wrong. Based on my experience with OpenTelemetry in different environments, OpenTelemetry was designed with flexibility in mind, supporting scenarios where telemetry is directly embedded within libraries, rather than requiring separate instrumentation libraries.

**Comment by lattwood** [comment] 2024-11-14 16:55
![Image](https://github.com/user-attachments/assets/66298bf9-6c75-4d2d-9463-d5ad9f71b03a)
![Image](https://github.com/user-attachments/assets/7eddfbd9-7820-4a5e-a47f-f87eb77aa097)

of course you don't, you're posting from your personal github account

**Comment by keller00** [comment] 2024-11-14 17:10
I think the point wasn't to appear as not a Snowflake employee. I think Bogdan used his personal account because he was making a post outside of normal work hours.

**Comment by lattwood** [comment] 2024-11-14 17:12
@keller00 then why refer to "Snowflake" rather than "I/we"? It's disingenuous at best and intentionally misleading at worst.

**Comment by bogdandrutu** [comment] 2024-11-14 18:24
>of course you don't, you work for Snowflake, and you're posting from your personal github account rather than @sfc-gh-bdrutu.

@lattwood I am doing this becausw @bogdandrutu may know something about OpenTelemetry, in case you did not trust what @sfc-gh-bdrutu said.

**Comment by mabdinur** [comment] 2024-11-14 20:35
The ddtrace library does not do anything unorthodox.  We simply implement the [opentelemetry context api](https://github.com/DataDog/dd-trace-py/blob/v2.17.0rc1/pyproject.toml#L52) and use the default implementation for all other components. ddtrace installs the opentelemetry-api but only configures support if DD_TRACE_OTEL_ENABLED=true is set (which honestly doesn't matter for this bug). 

I think this issue should be resolved in the `snowflake-connector-python`. The fix looks good to me: https://github.com/snowflakedb/snowflake-connector-python/pull/2106.

**Comment by bogdandrutu** [comment] 2024-11-14 22:01
@mabdinur 

Your "unorthodox" part is that you remove (somehow, not an expert in Python) the [`opentelemetry_propagator`](
https://github.com/open-telemetry/opentelemetry-python/blob/ccc9e6f71c2faf21e3ddf56d4c688c90dad8e46b/opentelemetry-api/pyproject.toml#L47) from the `entry-points`, which makes [inject](https://github.com/open-telemetry/opentelemetry-python/blob/ccc9e6f71c2faf21e3ddf56d4c688c90dad8e46b/opentelemetry-api/src/opentelemetry/propagate/__init__.py#L104) to throw an exception, but if someone uses directly the opentelemetry-api that does not throw.

**Closed** 2024-11-18 19:22 UTC
Labels: OpenTelemetry

**Comment by lattwood** [comment] 2024-12-04 20:13
@mabdinur so now we're seeing another fun error.

```
Failed to load context: contextvars_context, fallback to contextvars_context
Traceback (most recent call last):
  File "/var/task/opentelemetry/context/__init__.py", line 43, in _load_runtime_context
    return next(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

Due to this code- https://github.com/open-telemetry/opentelemetry-python/blob/415c94fb9834ce38459e58d5ee192a98494c4c76/opentelemetry-api/src/opentelemetry/context/__init__.py#L40-L64

I think `OTEL_PYTHON_CONTEXT` environment variable needs to be set to `ddcontextvars_context`?

https://github.com/DataDog/dd-trace-py/blob/4f7052e35ecbfc2ef5939ce5dd661952cc276d40/pyproject.toml#L52
