### ISSUE TITLE
Memory leak if traces created but trace agent not running

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [DataDog/dd-trace-py#972] opened 2019-06-20 14:27 UTC
It is possible to record traces/spans even if the trace-publishing agent is not running. The code does not issue any kind of warning to the logger and, importantly, it does not discard traces that can't be published. As such, the queue of unpublished traces just keeps growing to infinity. 

In an extremely short amount of time (< 1 hour), our application consumed over 600MB of memory before our orchestrator limited it and application errors started occurring. Took us about a day to figure it out—not terrible, but not great, either.

At the very least, this library should periodically issue a `WARNING` if traces are recorded but no trace agent is running to publish them. Ideally, however, both that would happen AND the queue would be size-limited so that 1) you know something is wrong, and 2) it doesn't cause your application to crash.

**Comment by nickwilliams-eventbrite** [comment] 2019-06-20 14:37
In case it helps, here's an explanation of how we got in this state: We're running a uWSGI/Django web application. We needed to customize the Datadog tracing middleware to do things slightly differently, so we couldn't insert `ddtrace.contrib.django` into `INSTALLED_APPS`, because that app forcibly inserts the original middleware (which we don't want) into Django's list of middleware. So we added the `DATADOG_TRACE` settings and inserted the middleware and called `patch_all` at startup, but he hadn't called `tracer.configure`, so spans recorded but the background agent that publishes traces never started.

**Comment by brettlangdon** [comment] 2019-06-20 15:13
hey @nickwilliams-eventbrite thanks for bringing to this our attention.

Whenever you import `ddtrace` we create a default global `Tracer` which calls `self.configure(...)` itself. https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/tracer.py#L48-L55

So there should be a background worker running.

If there is a writer and it fails to write to the trace agent (for whatever reason), those traces are dropped entirely, we do not hold on to them to retry or anything like that.

As well, we have some back pressure measures in place to ensure that we do not store more than 1000 traces in the queue between flushes. This generally means we cannot store or flush more than 1000 traces per second (give or take, `time.sleep(1)` plus flushing time makes this fuzzy).


The one that comes to my mind when I hear about this memory growth is, are you sure you are closing traces properly? If a trace is started and never closed, it will stay in memory and not get flushed to the background worker.

Does this issue occur with the build-in middleware (I understand if you can't test this based on your comments)?

Would you be willing to share the customizations you made to the middleware?

**Comment by nickwilliams-eventbrite** [comment] 2019-06-20 17:19
Yes, we're using the `with` block with all traces, so they are for sure getting closed. All I can tell you is what I observed: Using `tracemalloc`, I saw `ddtrace.span` and a few other `ddtrace` modules collectively holding on to tens of megabytes of data (thousands of spans with no spans closed) after about 1000 requests on a single uWSGI worker. When I added `tracer.config(...)` to our application startup, the problem completely went away and we were able to do over 14,000 requests with no growth in memory usage.

I'll have to review, consider, and discuss whether we can share the customizations.

**Comment by nickwilliams-eventbrite** [comment] 2019-06-20 17:21
Oh, we're currently using 0.17.1. I forgot to mention that.

**Comment by brettlangdon** [comment] 2019-06-20 17:54
Interesting that `tracer.configure(...)` solves the problem...

Wonder if upgrading to the latest version of `ddtrace==0.26.0` helps any, otherwise we might need to dig through our code a bit to see why something would be holding on to references.

**Comment by nickwilliams-eventbrite** [comment] 2019-06-20 19:18
Because this library is still beta and, so, doesn't strictly follow Semver, we're very cautious about upgrading it. We can look into trying out 0.26.0 sometime soon, but it won't happen quickly. We use it everywhere, and so upgrading poses significant risks to our platform.

**Comment by brettlangdon** [comment] 2019-06-20 19:28
Even though we are not a 1.x.x library, we take Semver very seriously and do everything we can to keep a stable library for our customers.

For most people upgrading should require little to no changes in your application code as a lot of what we provide is automatic/OOTB instrumentation.

We do however like to try to get people to upgrade to ensure they have access to the latest features and bug fixes.

However, I understand your concerns and respect your hesitation at blanket upgrading across your entire platform.

We will have to see if this is a behavior we can reproduce, but we might need some more information about how your tracer is configured or how you have uWSGI setup, etc.

If you'd prefer, you can email support@datadoghq.com and we can triage and discuss configuration/customizations in a less public place, if that helps.

**Comment by eedwards-sk** [comment] 2019-07-18 22:51
I've seen issues with ddtrace breaking semver before, so since what version did you start adhering to it?

**Comment by majorgreys** [comment] 2020-10-01 21:00
Due to the inactivity we'll close out this issue. If anyone is still experiencing a similar issue with memory leaks, please email support@datadoghq.com.

**Closed by majorgreys** 2020-10-01 21:00 UTC
