### ISSUE TITLE
AttributeError: module 'elasticsearch' has no attribute 'transport'

### ISSUE THREAD

**Issue by loren** [DataDog/dd-trace-py#5252] opened 2023-03-02 16:46 UTC
### Summary of problem
`ddtrace` 1.9.0 fails with this stack trace when using `elasticsearch` 8.6.2:
```
File "/usr/local/lib/python3.9/site-packages/ddtrace/_monkey.py", line 155, in on_import
    imported_module.patch()
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/elasticsearch/patch.py", line 47, in patch
    _patch(elasticsearch)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/elasticsearch/patch.py", line 54, in _patch
    _w(elasticsearch.transport, "Transport.perform_request", _get_perform_request(elasticsearch))
AttributeError: module 'elasticsearch' has no attribute 'transport'
```

We ran into this error when trying to upgrade packages. Pinning to these old versions works:
`ddtrace==1.4.4`
`elasticsearch==8.4.1`

I'm guessing it's related to [this PR](https://github.com/DataDog/dd-trace-py/pull/4139).

### Which version of dd-trace-py are you using?
1.9.0

### Which version of pip are you using?
pip 23.0.1 (python 3.9)

### Which libraries and their versions are you using?
elastic-transport                        8.4.0
elasticsearch                            8.6.2

**Comment by mabdinur** [comment] 2023-03-08 18:19
Hi @loren, 

I am closing this issue because it's a duplicate of https://github.com/DataDog/dd-trace-py/issues/3482. Elasticsearch8 is not yet supported. To run ddtrace without the elasticsearch integration run your application with: `DD_TRACE_ELASTICSEARCH_ENABLED=false`

**Closed by mabdinur** 2023-03-08 18:19 UTC
Labels: feature-request

**Comment by petroslamb** [comment] 2023-03-20 18:24
@mbdinur I tried the `DD_TRACE_ELASTICSEARCH_ENABLED=false` flag and it did not work for me.

```
ddtrace                  1.7.4
elastic-transport        8.4.0
elasticsearch            8.6.2
python      3.9.13
```
