### ISSUE TITLE
Warnings about traces being too large

### ISSUE THREAD

**Issue by Tenzer** [DataDog/dd-trace-py#1600] opened 2020-08-07 14:28 UTC
We have a Django application which we have instrumented with ddtrace. We regularly get warnings reported to our error tracking system with the messages "Trace is too big to fit in a payload, dropping it" and "Trace is larger than the max payload size, dropping it".

I can see the size of a payload is limited to 5 MB:
https://github.com/DataDog/dd-trace-py/blob/4222f54b7e8036f74fca685f0adb3251aacb5f6b/ddtrace/payload.py#L21-L23

Is there anything we could do to decrease the size of the payloads, or in any other way alleviate the problem?
If not, then I think we'll end up changing the log level from ddtrace to not emit warning level messages, since the warnings aren't very actionable for us.

**Comment by javiertejero** [comment] 2021-06-28 07:19
similar to #1577

**Comment by Kyle-Verhoog** [comment] 2021-07-28 21:02
Going to close as this is a duplicate of #1577 thanks for the report!

**Closed by Kyle-Verhoog** 2021-07-28 21:02 UTC
