### ISSUE TITLE
Timeout connecting to server -  Datadog Agent

### ISSUE THREAD

**Issue by lexicalunit** [DataDog/dd-trace-py#3645] opened 2022-04-28 18:14 UTC
### Which version of dd-trace-py are you using?
`ddtrace-run 1.0.2`

### Which version of pip are you using?
`21.1.1`

### Which version of the libraries are you using?
`ddtrace-1.0.2-cp39-cp39-macosx_10_9_universal2`

### How can we reproduce your problem?

First start the agent:
```
docker run --rm \
    --name dd-agent \
    -p8125:8125 \
    -p8126:8126 \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v /proc/:/host/proc/:ro \
    -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
    -e DD_API_KEY="OMIT" \
    -e DD_APP_KEY="OMIT" \
    -e DD_AGENT_MAJOR_VERSION="7" \
    -e DD_SERVICE="test-service" \
    -e DD_HOSTNAME="localhost" \
    -e DD_ENV="dev" \
    gcr.io/datadoghq/agent:7
```

Then try to send a trace:
```
$ export DD_TRACE_ENABLED="true"
$ export DD_API_KEY="OMIT"
$ export DD_APP_KEY="OMIT"
$ export DD_AGENT_MAJOR_VERSION=7
$ export DD_SERVICE="test-service"
$ export DD_HOSTNAME="localhost"
$ export DD_ENV="dev"
$ python
> from os import getenv
> from datadog import initialize
> from ddtrace import tracer
> initialize(api_key=getenv("DD_API_KEY"), app_key=getenv("DD_APP_KEY"))
> with tracer.trace(service="test_service", name="test_name"):
>     print("hello world")
```

### What is the result that you get?
There are no errors that come up in python, but over in the agent we see this error:
```log
2022-04-28 19:12:58 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:68 in Error) | check:redisdb | \
    Error running check: [{                                     \
        "message": "Timeout connecting to server",              \
        "traceback": "[see below]"                              \
    }]

Traceback (most recent call last): :
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 567, in connect
    sock = self._connect()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 625, in _connect
    raise err
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 613, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1071, in run
    self.check(instance)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 552, in check
    self._check_db()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 203, in _check_db
    info = conn.info()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/commands/core.py", line 626, in info
    return self.execute_command('INFO')
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py", line 1068, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 1173, in get_connection
    connection.connect()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 569, in connect
    raise TimeoutError("Timeout connecting to server")
redis.exceptions.TimeoutError: Timeout connecting to server
```

### What is the result that you expected?
I think this was working just a few weeks ago. It started failing for me in production and now I am trying to reproduce it locally too.

**Comment by Kyle-Verhoog** [comment] 2022-04-28 18:51
🤔 I don't think we've changed anything related to the connection defaults recently. @lexicalunit can you double check that the agent is running and reachable?

You should get a 404 when curling `http://localhost:8126/`:
```
(.venv) ~/d/dd-trace-py ❯❯❯ curl http://localhost:8126/
404 page not found
```

**Comment by lexicalunit** [comment] 2022-04-28 19:16
Sorry, I completely forgot some steps in my reproduction! For one, instead of `$ python` it should be `$ ddtrace-run python`

For another I completely left out starting up the agent! 😓 

Let me edit the original post as the error I'm getting now that I have things set up correctly is slightly different.

**Comment by lexicalunit** [comment] 2022-04-28 19:31
Do I need to run a redis server? I ... don't remember that being a requirement before now. I definitely don't have one in production and things have been working fine for many months there.

**Comment by Kyle-Verhoog** [comment] 2022-04-28 20:09
Ah yeah so it's on the agent side, could you reach out to support@datadoghq.com @lexicalunit? We only handle issues related to the `ddtrace` Python library here 🙂 

That said, I don't think this error should be interfering with any functionality, it's just the agent redis check that is failing. I wouldn't expect the check to fail that loudly if no redis instance was found. My only guess would be that the agent check is enabled through the Datadog UI and that configuration is being applied to your local agent and so the redis check runs and fails.

I'm going to close the issue here but if you suspect it is related to something in `ddtrace`, feel free to reopen it 🙂

**Comment by lexicalunit** [comment] 2022-04-28 23:10
Thanks! I'll follow up with them.

**Comment by Mykhailo-Dubovskyi** [comment] 2022-06-07 17:12
How was it fixed i had the same error ?
i had that error into docker dd agent

**Comment by lexicalunit** [comment] 2022-06-07 17:37
@Mykhailo-Dubovskyi sorry, I haven't reached out to datadog support yet as it hasn't been a priority for me. I do still get this error. 🤷🏻‍♀️

**Comment by liam-bilich** [comment] 2022-08-31 13:47
Having the same issue,
we have a redis alpine running in container with a password,
DataDog is not able to connect to, giving the same errors.

We have a dotnet app container that connects to it properly
and I'm also able to use the redis-cli and connect without a password
from the localhost machine.

Yet DataDog agent (running in the same network also as a container) is refusing.

      Last Execution Date : 2022-08-31 13:44:11 UTC (1661953451000)
      Last Successful Execution Date : Never
      Error: Timeout connecting to server
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 614, in connect
          sock = self.retry.call_with_retry(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/retry.py", line 50, in call_with_retry
          raise error
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/retry.py", line 45, in call_with_retry
          return do()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 615, in <lambda>
          lambda: self._connect(), lambda error: self.disconnect(error)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 680, in _connect
          raise err
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 668, in _connect
          sock.connect(socket_address)
      socket.timeout: timed out

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1120, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 552, in check
          self._check_db()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py", line 203, in _check_db
          info = conn.info()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/commands/core.py", line 900, in info
          return self.execute_command("INFO", **kwargs)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py", line 1192, in execute_command
          conn = self.connection or pool.get_connection(command_name, **options)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 1386, in get_connection
          connection.connect()
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py", line 618, in connect
          raise TimeoutError("Timeout connecting to server")
      redis.exceptions.TimeoutError: Timeout connecting to server
      
      
      
we use a host network, and the Redis should be available on the localhost via port 6379.

Any ideas?

**Comment by Mykhailo-Dubovskyi** [comment] 2022-08-31 13:54
> @Mykhailo-Dubovskyi sorry, I haven't reached out to datadog support yet as it hasn't been a priority for me. I do still get this error. 🤷🏻‍♀️

does not pay attention on this . its do not have any impact on collection and sending data

**Comment by jason-hwang** [comment] 2023-08-07 08:15
Hi guys, Is there any update?

**Comment by P403n1x87** [comment] 2023-08-07 11:01
@jason-hwang Apologies for the wait. Does this still happen with the latest ddtrace release? Would you happen to have a minimal reproducer to share? Thanks.

**Comment by brettlangdon** [comment] 2023-08-07 12:50
> Hi guys, Is there any update? It still happens...
> 
> ```shell
> 2023-08-07 07:59:15 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:redisdb | Error running check: [{"message": "Timeout connecting to server", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 614, in connect\n
> 2023-08-07 07:59:19 UTC | CORE | INFO | (pkg/collector/worker/check_logger.go:57 in CheckFinished) | check:container | Done running check
> ```

@jason-hwang that looks like a log from the Datadog agent for the redis check?

This repository is for the `ddtrace` Python package.

It is probably better report over at https://github.com/DataDog/datadog-agent/ or https://github.com/DataDog/integrations-core

**Comment by P403n1x87** [comment] 2023-08-07 13:23
Closing again for the same reason: this does not appear to be related to ddtrace. The repositories mentioned above are more likely the better place to report this issue.

**Closed by P403n1x87** 2023-08-07 13:23 UTC

**Comment by jason-hwang** [comment] 2023-08-08 01:10
@P403n1x87 @brettlangdon 
Oh, I apologize for leaving you with unclear logs and information.
I ran into this problem while working through the [following guide](https://docs.datadoghq.com/database_monitoring/setup_mysql/aurora?tab=docker)

```shell
docker run -e "DD_API_KEY=${DD_API_KEY}" \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -l com.datadoghq.ad.check_names='["mysql"]' \
  -l com.datadoghq.ad.init_configs='[{}]' \
  -l com.datadoghq.ad.instances='[{
    "dbm": true,
    "host": "<AWS_INSTANCE_ENDPOINT>",
    "port": 3306,
    "username": "datadog",
    "password": "<UNIQUEPASSWORD>"
  }]' \
  gcr.io/datadoghq/agent:${DD_AGENT_VERSION}
```

I will report to `datadog-agent` repository. thanks all.
