### ISSUE TITLE
error logs when HTTP requests come from Datadog Synthetics

### ISSUE THREAD

**Issue by sileht** [DataDog/dd-trace-py#6831] opened 2023-09-05 08:53 UTC
### Summary of problem

ddtrace is reporting the following issues in our logs:

```
ERROR: received invalid w3c traceparent: 00-00000000000000002743c6bec8a9c773-0000000000000000-01 , 1 additional messages skipped:

ValueError: 0 value for span_id is invalid
  File "ddtrace/propagation/http.py", line 718, in _extract
    trace_id, span_id, sampling_priority = _TraceContext._get_traceparent_values(tp)
  File "ddtrace/propagation/http.py", line 639, in _get_traceparent_values
    raise ValueError("0 value for span_id is invalid")
```

### Which version of dd-trace-py are you using?

1.17.3

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiofiles==23.2.1
alabaster==0.7.13
alembic==1.12.0
anyio==3.7.1
anys==0.2.1
asgi-lifespan==2.1.0
attrs==23.1.0
Authlib==1.2.1
Babel==2.12.1
beautifulsoup4==4.12.2
black==23.7.0
boltons==21.0.0
bracex==2.3.post1
bytecode==0.15.0
cattrs==23.1.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
click-option-group==0.5.6
colorama==0.4.6
coverage==7.3.0
cryptography==41.0.3
daiquiri==3.2.1
datadog==0.46.0
ddsketch==2.0.4
ddtrace==1.17.3
deepdiff==6.4.1
defusedxml==0.7.1
Deprecated==1.2.14
docutils==0.20.1
dulwich==0.21.6
envier==0.4.0
execnet==2.0.2
face==22.0.0
fastapi==0.103.1
filelock==3.12.3
first==2.0.2
freezegun==1.2.2
glom==22.1.0
graphql-utils==0.4
greenlet==2.0.2
gunicorn==21.2.0
h11==0.14.0
h2==4.1.0
hiredis==2.2.3
honcho==1.1.0
hpack==4.0.0
httpcore==0.17.3
httptools==0.6.0
httpx==0.24.1
hyperframe==6.0.1
idna==3.4
imagesize==1.4.1
imia==0.5.3
importlib-metadata==6.8.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
Mako==1.2.4
markdown-it-py==3.0.0
markdownify==0.11.6
MarkupSafe==2.1.3
mdurl==0.1.2
msgpack==1.0.5
multidict==6.0.4
mypy==1.5.1
mypy-extensions==1.0.0
numpy==1.25.2
opentelemetry-api==1.19.0
ordered-set==4.1.0
packaging==23.1
passlib==1.7.4
pastel==0.2.1
pathspec==0.11.2
pbr==5.11.1
peewee==3.16.3
pgvector==0.2.1
platformdirs==3.10.0
pluggy==1.3.0
poethepoet==0.22.1
protobuf==4.24.2
psycopg==3.1.10
psycopg-binary==3.1.10
pycparser==2.21
pydantic==1.10.12
pyenchant==3.2.2
Pygments==2.16.1
PyJWT==2.8.0
pytest==7.4.1
pytest-asyncio==0.21.1
pytest-cov==4.1.0
pytest-github-actions-annotate-failures==0.2.0
pytest-rerunfailures==12.0
pytest-split==0.8.1
pytest-timeout==2.1.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-lsp-jsonrpc==1.0.0
python-multipart==0.0.6
PyYAML==6.0.1
redis==5.0.0
referencing==0.30.2
regex==2023.8.8
reno==4.0.0
requests==2.31.0
respx==0.20.2
rich==13.5.2
rpds-py==0.10.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
ruff==0.0.287
semgrep==1.38.3
sentry-sdk==1.30.0
setproctitle==1.2.3
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.5
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sphinxcontrib-spelling==8.0.0
SQLAlchemy==2.0.20
SQLAlchemy-Utils==0.41.1
starlette==0.27.0
starsessions==2.1.2
tenacity==8.2.3
tiktoken==0.4.0
tomli==2.0.1
types-first==2.0.5.2
types-freezegun==1.1.10
types-pkg-resources==0.1.3
types-pyOpenSSL==23.2.0.2
types-python-dateutil==2.8.19.14
types-PyYAML==6.0.12.11
types-redis==4.6.0.4
typing_extensions==4.7.1
ujson==5.8.0
Unidecode==1.3.6
urllib3==1.26.16
uvicorn==0.23.2
uvloop==0.17.0
vcrpy==5.1.0
voluptuous==0.13.1
watchfiles==0.20.0
wcmatch==8.5
websockets==11.0.3
wrapt==1.15.0
xmltodict==0.13.0
yamllint==1.32.0
yarl==1.9.2
zipp==3.16.2
</details>

### How can we reproduce your problem?

The error is when the HTTP request is done by Datadog synthetics Tests, here the request headers:
```
{
accept: '*/*', 
authorization: [Filtered], 
connection: 'close', 
host: 'XXXXXX', 
sec-datadog: 'Request sent by a Datadog Synthetics API Test (https://docs.datadoghq.com/synthetics/) - test_id: 5p7-86s-h76', 
user-agent: 'Datadog/Synthetics', 
x-datadog-origin: 'synthetics', 
x-datadog-parent-id: '0', 
x-datadog-sampling-priority: '1', 
x-datadog-trace-id: '1051615846866237863'
}
```

### What is the result that you get?

ddtrace is reporting the following issues in our logs:

```
ERROR: received invalid w3c traceparent: 00-00000000000000002743c6bec8a9c773-0000000000000000-01 , 1 additional messages skipped:

ValueError: 0 value for span_id is invalid
  File "ddtrace/propagation/http.py", line 718, in _extract
    trace_id, span_id, sampling_priority = _TraceContext._get_traceparent_values(tp)
  File "ddtrace/propagation/http.py", line 639, in _get_traceparent_values
    raise ValueError("0 value for span_id is invalid")
```

### What is the result that you expected?

No error in logs

**Comment by AnaelGorfinkel** [comment] 2023-09-05 09:25
Hey, this error is also happened in our code yesterday. 
Our version: 1.14.0

**Comment by heavenshell** [comment] 2023-09-05 10:01
Same error is also happening.
Our version: ddtrace==1.18.3

**Comment by dshunfen** [comment] 2023-09-05 13:30
Confirmed we're also seeing this on version `1.17.2`

**Comment by kamraz** [comment] 2023-09-05 14:28
Saw this on version `1.17.2` caused by synthetics requests.

Errors started and stopped at the same times as mentioned above.

**Comment by mabdinur** [comment] 2023-09-11 17:14
Hi, 

Thanks for bringing this to our attention. This issue was triggered by a change to an internal service on September 4th. This issue was resolved by ensuring internal services propagated synthetics http headers using the Datadog format instead of W3C. This fix was rolled out on Tues Sept 5.

**Closed by mabdinur** 2023-09-11 17:14 UTC

**Comment by sileht** [comment] 2023-09-11 17:52
Thanks!
