### ISSUE TITLE
Release notes page inaccurate

### ISSUE THREAD

**Issue by adamchainz** [DataDog/dd-trace-py#2000] opened 2021-02-08 17:11 UTC
https://ddtrace.readthedocs.io/en/stable/release_notes.html

This page lists 0.46 release candidates 1 and 2, however no such releases exist on PyPI: https://pypi.org/project/ddtrace/#history

The page also doesn't recognize that a non-release candidate 0.46 exists, which would be good to note whether anything changed from the RC's or not.

**Comment by majorgreys** [comment] 2021-02-09 14:14
Thanks for raising this! We have noticed it and plan to address it. Our release process currently includes release candidates which are not yet pushed to pypi. We are using reno to generate the release notes in which we've had to include RCs as they otherwise did not group notes with the correct release tags.

**Comment by jd** [comment] 2021-02-09 15:00
This problem, in particular, is because `v0.46.0` and `v0.46.0rc2` are the same git tag and reno, for whatever reason, picks the latter.

**Comment by jd** [comment] 2021-02-09 15:35
I tested locally and the output is the one expected:

![Screenshot 2021-02-09 at 16 34 24](https://user-images.githubusercontent.com/2644/107387016-b4093980-6af4-11eb-8c1e-c31727af0050.png)

The problem is likely that readthedocs did not re-trigger the branch build when the new tag was pushed. @brettlangdon can you check if we can retrigger a build when a new tag is pushed?

**Comment by jd** [comment] 2021-02-10 14:20
I sent a fix upstream so reno would select the right tag when multiple tags are available for a commit:
https://review.opendev.org/c/openstack/reno/+/774867

**Comment by Kyle-Verhoog** [comment] 2022-01-20 18:52
This looks to have been finally resolved in #3085

**Closed by Kyle-Verhoog** 2022-01-20 18:52 UTC
Labels: bug, docs
