### ISSUE TITLE
Already mutably borrowed

### ISSUE THREAD

**Issue by mro-rhansen2** [DataDog/dd-trace-py#10002] opened 2024-07-30 23:46 UTC
### Summary of problem
Our program is generating what appears to be an error message related to Rust bindings.

We are seeing this error when executing a multithreaded program but only when it is launched through ddtrace-run:

RuntimeError: Already mutably borrowed

Here's partial a stack trace from DataDog:

```
RuntimeError: Already mutably borrowed

return self.rate_limit != DEFAULT_SAMPLING_RATE_LIMIT
File "/usr/local/lib/python3.11/site-packages/ddtrace/internal/rate_limiter.py", line 22, in _has_been_configured

if self.limiter._has_been_configured:
File "/usr/local/lib/python3.11/site-packages/ddtrace/sampler.py", line 342, in _choose_priority_category_with_rule

self._choose_priority_category_with_rule(matched_rule, sampler),
File "/usr/local/lib/python3.11/site-packages/ddtrace/sampler.py", line 326, in sample

self._sampler.sample(span)
File "/usr/local/lib/python3.11/site-packages/ddtrace/_trace/tracer.py", line 325, in sample

ddtrace.tracer.sample(root_span)
File "/usr/local/lib/python3.11/site-packages/ddtrace/propagation/http.py", line 996, in inject

HTTPPropagator.inject(span.context, request.headers)
File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/requests/connection.py", line 106, in _wrap_send
```

### Which version of dd-trace-py are you using?
2.10.1

### Which version of pip are you using?
22.3.1

### Which libraries and their versions are you using?
attrs~=23.2.0
environs~=9.3.5
click~=8.0.3
pandas>=2.0.0,<2.1.0
pyarrow>=14.0.1,<15
numpy>=1.22.4,<2
pytz>=2020.1,<2024.1
snowflake-connector-python[pandas]>=3,<4
snowflake-sqlalchemy
sqlalchemy<2.0.0,>=1.4.0 # 2.0.0 breaks snowflake-sqlalchemy
requests>=2.0.0,<3.0.0
urllib3>=1.21.1,<2.0.0
pyyaml~=6.0
jinja2>=3.1.2,<4.0.0
kafka-python
cachetools~=4.2.4
python-dateutil>=2.8.2
redis[hiredis]>=5,<6
splitio_client[cpphash]==9.1.0
deprecated
perfcounters~=2.1.0
inflection
pymongo[srv]>=4.6.0,<4.7.0
uvloop~=0.18.0; 
quattro~=0.3
apscheduler~=3.9.1
motor>=3.3.0,<3.4.0
aiokafka~=0.7.2
python-json-logger~=2.0.2
Office365-REST-Python-Client~=2.4.2
smbprotocol~=1.10.1
tornado~=6.1
setuptools>=69,<70

### What is the result that you get?
A runtime error within ddtrace is bubbling into our application's workflow.

### What is the result that you expected?
All errors within ddtrace should be logged but should never be allowed to interfere with program execution.

**Comment by emmettbutler** [comment] 2024-07-31 20:15
Thanks for reporting this, @mro-rhansen2. We recently ported the rate limiter to Rust and it looks like this error slipped through the cracks. cc @brettlangdon

**Comment by doudoujay** [comment] 2024-07-31 20:26
```
Traceback (most recent call last):
  File "/dd_tracer/python/ddtrace/_trace/processor/__init__.py", line 365, in on_span_finish
    spans = tp.process_trace(spans)
  File "/dd_tracer/python/ddtrace/_trace/processor/__init__.py", line 166, in process_trace
    self.sampler.sample(trace[0])
  File "/dd_tracer/python/ddtrace/sampler.py", line 326, in sample
    self._choose_priority_category_with_rule(matched_rule, sampler),
  File "/dd_tracer/python/ddtrace/sampler.py", line 342, in _choose_priority_category_with_rule
    if self.limiter._has_been_configured:
  File "/dd_tracer/python/ddtrace/internal/rate_limiter.py", line 22, in _has_been_configured
    return self.rate_limit != DEFAULT_SAMPLING_RATE_LIMIT
RuntimeError: Already mutably borrowed
```
We are also observing this. Do you know whats the eta for this fix?

**Comment by mro-rhansen2** [comment] 2024-08-01 14:18
> Thanks for reporting this, @mro-rhansen2. We recently ported the rate limiter to Rust and it looks like this error slipped through the cracks. cc @brettlangdon

You bet. Looking forward to a resolution.

@doudoujay We were able to work around the issue by reverting to ddtrace 2.9.3 for the time being.

**Comment by emmettbutler** [comment] 2024-08-01 15:14
If anyone can offer a simple reproducer, that would be helpful.

**Comment by veggiesaurus** [comment] 2024-08-03 08:02
This issue was an absolute pain to debug, because it affected our docker-compose commands executed via SSM, and prevented us from reliably deploying 😢 

For now I worked around it by pinning our `datadog-api-library-python` package:

```bash
apt-get install datadog-apm-library-python=2.9.2-1
apt-mark hold datadog-apm-library-python
```

Thank you for the suggestion @mro-rhansen2 👍🏻

**Comment by christianbundy** [comment] 2024-08-06 18:14
Is this causing latency or memory allocation spikes for anyone else? We upgraded from 2.9.3 to 2.10.3 and our P99 latency doubled. In the Datadog profiler we went from 20 MiB allocated per minute to 1 GiB allocated per minute, and reverting the upgrade resolved this. We only saw "Already mutably borrowed" about 50 times in a 4-hour period, but our performance was significantly degrade the whole time.

**Comment by brettlangdon** [comment] 2024-08-13 13:57
2.10.5 has been released with #10176 which should fix this issue (it is on PyPI, but may take a bit for all artifacts to get released).

If people could please upgrade to that version. Please feel free to re-open if the issue is not fully resolved!

**Comment by VanyaDNDZ** [comment] 2024-08-14 14:42
I wasn't able to reproduce that bug with real flow or inside of running program, but I have a code that can show that issue still exists if `RateLimiter` accessed without proper locking on python side. 
```
from concurrent.futures import ThreadPoolExecutor
import random
from functools import partial

from ddtrace.internal.rate_limiter import RateLimiter


def blocking_io(limiter):
    event_type = "bug_io"
    limiter.is_allowed(event_type)
    with open('/dev/urandom', 'rb') as f:
        return f.read(random.randint(1, 1024))


def main():
    limiter = RateLimiter(1)
    fn = partial(blocking_io, limiter)
    results = []
    with ThreadPoolExecutor(max_workers=4) as pool:
        for _ in range(10000):
            results.append(pool.submit(fn))
    for result in results:
        result.result()


if __name__ == '__main__':
    main()
```
I tried it with the latests versions of ddtrace (2.10.5). 
This is not happening when I'm trying to access any property of RateLimiter. 

I think proper fix would be replace `&mut self` to `&self` and relay on interior mutability to change internal `rate_limiter`
```
pub fn _is_allowed(&self, py: Python<'_>, timestamp_ns: f64) -> bool {
        py.allow_threads(|| self.rate_limiter.lock().unwrap()._is_allowed(timestamp_ns))
    }
``` 

Unfortunately I cannot build detract locally to check if that will fix an issue

**Comment by brettlangdon** [comment] 2024-08-14 15:31
@VanyaDNDZ thanks for reporting, I saw another report that it is not resolved.

I have opened up https://github.com/DataDog/dd-trace-py/pull/10225 to just revert the rust rate limiter. we don't gain enough from the change for the headaches it has provided.

**Closed** 2024-08-14 17:20 UTC

**Comment by wadinj** [comment] 2024-08-21 08:13
FYI, we still have the issue on 2.11 somehow
