### ISSUE TITLE
Error installing ddtrace 0.32.2 from pipenv

### ISSUE THREAD

**Issue by DazEdword** [DataDog/dd-trace-py#1178] opened 2020-01-10 13:58 UTC
### Which version of dd-trace-py are you using?
 0.32.2

### How can we reproduce your problem?
- Add `ddtrace = "==0.32.2"` to pipenv
- Run `pipenv update`.

### What is the result that you get?
`An error occurred while installing ddtrace==0.32.2 `

### What is result that you expected?
Correct installation.

Note: installing  `0.32.0` works perfectly fine.

**Comment by brettlangdon** [comment] 2020-01-10 14:27
@DazEdword which version of Python are you using?

**Comment by DazEdword** [comment] 2020-01-10 14:30
Hey @brettlangdon 

That's 3.6

**Comment by brettlangdon** [comment] 2020-01-10 14:35
thanks, let me try to reproduce locally.

would you be willing to run `pipenv update --verbose`? it _should_ help show the error it is seeing.

**Comment by DazEdword** [comment] 2020-01-10 14:47
It seems that it's struggling to find it in the pypi indices, I can see many instances with different versions and architectures such as this:

```
Skipping link: none of the wheel's tags match: cp27-cp27m-manylinux1_i686: https://files.pythonhosted.org/packages/f3/6a/1af012efbb50742fa3c6a8f33c124f71405eb66728a704f663012fdd66b2/ddtrace-0.28.0-cp27-cp27m-manylinux1_i686.whl#sha256=bb1d7bc5218f36d5254e8fc00040ce6d13106ab2d5dc1e14812af22e86270170 (from https://pypi.org/simple/ddtrace/)
```

My local OS is:

```
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
```

**Comment by majorgreys** [comment] 2020-01-10 15:34
@DazEdword, I'm trying to reproduce this issue on our end, but not seeing it crop up.

My steps for reproducing this on a Mac has been:

```
# inside a fresh virtualenv with Python 3.6.9
pip install pipenv
pipenv --python 3.6.9
pipenv install ddtrace==0.32.2
pipenv run ddtrace-run python -c "import ddtrace; print(ddtrace.__version__)"
```

The library installs and the run command prints the expected `0.32.2`.

As a caveat, this was on Mac OS 10.14, though as you note you are on 10.15.

Can you share a link to the output of `pipenv update --verbose`?

**Comment by majorgreys** [comment] 2020-01-10 15:48
@DazEdword I think I now have reproduced your issue by first installing `ddtrace==0.32.0` and then running `pipenv update`.

The error I am getting from `pipenv update`:

```
/private/var/folders/9_/k78_39fn08991mz6r_ws9fc00000gn/T/pip-build-env-w01hhfya/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
  Traceback (most recent call last):
    File "/Users/tahir.butt/.asdf/installs/python/3.6.9/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/tahir.butt/.asdf/installs/python/3.6.9/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/tahir.butt/.virtualenvs/tempenv-724e24107f6e/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.main import main as _main  # isort:skip # noqa
    File "/Users/tahir.butt/.virtualenvs/tempenv-724e24107f6e/lib/python3.6/site-packages/pip/_internal/__init__.py", line 2, in <module>
      import pip._internal.utils.inject_securetransport  # noqa
    File "/Users/tahir.butt/.virtualenvs/tempenv-724e24107f6e/lib/python3.6/site-packages/pip/_internal/utils/inject_securetransport.py", line 36, in <module>
      inject_securetransport()
    File "/Users/tahir.butt/.virtualenvs/tempenv-724e24107f6e/lib/python3.6/site-packages/pip/_internal/utils/inject_securetransport.py", line 20, in inject_securetransport
      import ssl
    File "/Users/tahir.butt/.asdf/installs/python/3.6.9/lib/python3.6/ssl.py", line 94, in <module>
      import textwrap
    File "/Users/tahir.butt/.asdf/installs/python/3.6.9/lib/python3.6/textwrap.py", line 8, in <module>
      import re
    File "/Users/tahir.butt/.virtualenvs/tempenv-724e24107f6e/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  Installing build dependencies: finished with status 'error'
```

I will continue investigating.

**Comment by DazEdword** [comment] 2020-01-10 15:55
@majorgreys @brettlangdon 

Thanks for your help! Tried on a newly created pipenv and it installs with no errors here as well. It fails on a private repository that includes a private Fury index (although it is not marked as the primary index, but the extra one). I definitely have seen that enum error before, but can't find it in the output I've captured (and redacted).

[ddtrace_pipenv-verbose.txt](https://github.com/DataDog/dd-trace-py/files/4046455/ddtrace_pipenv-verbose.txt)

**Comment by majorgreys** [comment] 2020-01-10 17:56
Upon further investigation, `pipenv install ddtrace=0.32.0` results in `enum34` being installed (which is the incorrect behavior) whereas `pipenv install ddtrace==0.32.2` does not (which is correct).

The backport `enum34` should only be installed for Python versions before 3.4. This was introduced with the 0.32.0 release with a conditional `install_requires`:

```python
if sys.version_info[:2] < (3, 4):
    install_requires.extend(["enum34"])
```

https://github.com/DataDog/dd-trace-py/blob/v0.32.0/setup.py#L62-L64

This approach was modified in #1174 using environment markers and released in the patch release 0.32.1.

We can see this issue surface if we use the `pipenv-resolver` tool:

```
$ pipenv-resolver ddtrace==0.32.0
RESULTS:
[{"version": "5.6.7", "hashes": [...], "name": "psutil"}, {"version": "1.1.6", "hashes": [...], "name": "enum34"}, {"version": "0.32.0", "hashes": [...], "name": "ddtrace"}]
$ pipenv-resolver ddtrace==0.32.1
RESULTS:
[{"version": "0.32.1", "hashes": [...], "name": "ddtrace"}, {"version": "5.6.7", "hashes": [...], "name": "psutil"}]
``` 

As an upgrade path for users of `pipenv`, I would advise uninstalling `ddtrace` and then installing again. 

Unfortunately `pipenv uninstall ddtrace` did not work for me, as it left the `Pipfile` as is. Instead, I manually removed `ddtrace` from the `Pipfile`, executed `pipenv clean` to successfully uninstall `ddtrace` and its dependencies, and then reinstalled with `pipenv install ddtrace==0.32.2`.

@DazEdword, can you confirm that this upgrade workaround addresses the issue you were having with updating?

Strangely enough, I don't see this issue when using the official Docker image:

```
docker run -it -w /tmp/ --rm python:3.6.9 bash
root@41ce7f95380a:/tmp# pip install pipenv
...
root@41ce7f95380a:/tmp# pipenv install ddtrace==0.32.0
...
root@41ce7f95380a:/tmp# pipenv graph
ddtrace==0.32.0
  - psutil [required: >=5.0.0, installed: 5.6.7]
root@41ce7f95380a:/tmp# pipenv-resolver ddtrace==0.32.0
RESULTS:
[{"version": "5.6.7", "hashes": [...], "name": "psutil"}, {"version": "0.32.0", "hashes": [...], "name": "ddtrace"}]
```

**Comment by majorgreys** [comment] 2020-01-10 17:57
@JBKahn, you might have more thoughts to share into this issue since you were also experiencing upgrading issues, but with `poetry`.

**Comment by JBKahn** [comment] 2020-01-10 19:54
++ I had a "similar" issue with poetry. If you re-lock your deps and re-create the virtualenv it should just work. It's because enum34 was installed and now isn't required but it being present at install time is what causes the error.

**Comment by DazEdword** [comment] 2020-01-13 09:16
@majorgreys Workaround does the trick for us too.

**Comment by JBKahn** [comment] 2020-01-14 15:06
Close this issue @DazEdword @majorgreys ?

**Closed** 2020-01-14 15:49 UTC
