### ISSUE TITLE
[psycopg2] The prepare functions require psycopg2.extensions.connection.

### ISSUE THREAD

**Issue by Prillan** [DataDog/dd-trace-py#383] opened 2017-11-27 13:37 UTC
Here is an example:

```
from ddtrace import patch_all

patch_all()

import psycopg2
from psycopg2.extensions import adapt

conn = psycopg2.connect(dbname="test")

items = adapt([1, 2, 3])
items.prepare(conn) # Fails here

binary = adapt(b'12345')
binary.prepare(conn) # and here.
```

```
$ python example.py
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    items.prepare(conn)
TypeError: argument 1 must be psycopg2.extensions.connection, not TracedConnection
```

This could probably be solved in a similar manner to #96 .

**Comment by NilsJPWerner** [comment] 2017-12-07 19:47
I too am having this issue.

**Comment by Kyle-Verhoog** [comment] 2018-06-04 15:38
@Prillan, @NilsJPWerner are you still having this problem? It appears as though a fix was merged to fix this a while back.

**Comment by Prillan** [comment] 2018-06-05 12:11
I probably won't get around to test this _properly_ anytime soon, but I can confirm that the test code in my post above no longer crashes.

Thanks for the heads up @Kyle-Verhoog !

**Comment by palazzem** [comment] 2018-06-12 14:06
If the testing code at top of the thread is considered fixed, I guess we can close this issue and release the 0.12.1. If the problem is spotted again, feel free to reopen the issue!

**Closed** 2018-06-12 14:07 UTC
Labels: bug, integrations
