### ISSUE TITLE
ddtrace failed to wrap beanie and pymongo

### ISSUE THREAD

**Issue by riven314** [DataDog/dd-trace-py#6757] opened 2023-08-25 06:24 UTC
### Summary of problem
When my service is deployed with datadog plugin, it crashed due to incompatibility with beanie and pymongo.

The attached are the errors that I got:
![Screenshot 2023-08-25 at 2 18 12 PM](https://github.com/DataDog/dd-trace-py/assets/21143399/be03590a-0d8c-40d2-a0e4-4c2c121bfde7)
![Screenshot 2023-08-25 at 2 19 42 PM](https://github.com/DataDog/dd-trace-py/assets/21143399/e7026966-9ad7-4d45-9b3e-87903315b94d)

### Which version of dd-trace-py are you using?
latest version as of now

### Which version of pip are you using?
NA

### Which libraries and their versions are you using?

the forked beanie is in version 1.21.0
```
appnope==0.1.3
asttokens==2.2.1
backcall==0.2.0
beanie @ git+https://github.com/riven314/beanie.git@6dda4daf13e440955633e6bbdb99abccecbca5fa
black==22.12.0
boto3==1.28.23
botocore==1.31.23
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.6
cloudpickle==2.2.1
confluent-kafka==2.2.0
contourpy==1.1.0
coverage==6.5.0
cycler==0.11.0
dask==2023.3.0
decorator==5.1.1
dnspython==2.4.2
exceptiongroup==1.1.2
executing==1.2.0
flake8==5.0.4
Flake8-pyproject==1.2.3
fonttools==4.42.0
fsspec==2023.6.0
idna==3.4
iniconfig==2.0.0
ipython==8.14.0
isort==5.12.0
jedi==0.19.0
jmespath==1.0.1
kiwisolver==1.4.4
lazy-model==0.1.0b0
locket==1.0.0
matplotlib==3.7.2
matplotlib-inline==0.1.6
mccabe==0.7.0
motor==3.1.2
mypy==0.991
mypy-extensions==1.0.0
numpy==1.25.2
odmantic==0.9.2
opencv-python==4.8.0.76
packaging==23.1
pandas==1.5.3
parso==0.8.3
partd==1.4.0
pathspec==0.11.2
patsy==0.5.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
plotly==5.15.0
pluggy==1.2.0
prompt-toolkit==3.0.39
ptyprocess==0.7.0
pure-eval==0.2.2
pycodestyle==2.9.1
pydantic==1.10.12
pyflakes==2.5.0
Pygments==2.16.1
pymongo==4.4.1
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.20.3
pytest-cov==4.1.0
pytest-randomly==3.13.0
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
s3transfer==0.6.1
scipy==1.10.1
shellcheck-py==0.8.0.4
six==1.16.0
stack-data==0.6.2
statsmodels==0.14.0
tenacity==8.2.2
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
traitlets==5.9.0
trimesh==3.23.1
typing_extensions==4.7.1
urllib3==1.26.16
wcwidth==0.2.6
xgboost==1.7.6
```

**Comment by mabdinur** [comment] 2023-08-28 18:03
Duplicate of https://github.com/DataDog/dd-trace-py/issues/6723. This issue should be resolved by: https://github.com/DataDog/dd-trace-py/pull/6775

**Closed by mabdinur** 2023-08-28 18:03 UTC
