### ISSUE TITLE
Unable to install ddtrace==0.37.0 on python:2.7-alpine

### ISSUE THREAD

**Issue by jorns** [DataDog/dd-trace-py#1427] opened 2020-05-12 06:46 UTC
### Which version of dd-trace-py are you using?
0.37

### How can we reproduce your problem?
```
FROM python:2.7-alpine

RUN pip install --upgrade pip=='20.1'
RUN echo "ddtrace" > requirements.txt
RUN pip install -r requirements.txt
```
### What is the result that you get?
```
gcc -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python2.7 -c ddtrace/profiling/collector/stack.c -o build/temp.linux-x86_64-2.7/ddtrace/profiling/collector/stack.o -DPy_BUILD_CORE
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ddtrace
  Building wheel for msgpack (setup.py): started
  Building wheel for msgpack (setup.py): finished with status 'done'
  Created wheel for msgpack: filename=msgpack-1.0.0-py2-none-any.whl size=15867 sha256=50773a85de511c5cc613423c0bcc86ab2b8639f30d3fdc602226e0265910dee8
  Stored in directory: /root/.cache/pip/wheels/5d/81/b7/1c22431733600a824e7209fe6b885a6f8daa6758498e848569
Successfully built msgpack
Failed to build ddtrace
ERROR: Could not build wheels for ddtrace which use PEP 517 and cannot be installed directly
```

**Comment by jd** [comment] 2020-05-12 08:41
Duplicate of #1388, though in your case you also need to install `gcc` as it shows:
`unable to execute 'gcc': No such file or directory`

**Closed by jd** 2020-05-12 08:41 UTC
