### ISSUE TITLE
"cannot decode v0.3 services payload" error when tracing aiopg

### ISSUE THREAD

**Issue by k4nar** [DataDog/dd-trace-py#492] opened 2018-06-18 15:34 UTC
I have a Python application using aiopg and monitored by Datadog. When starting, it sends a bad frame to `trace-agent` and then everything goes fine.

Versions:
- datadog-agent: 6.2.1
- ddtrace-py: 0.12.1
- aiopg: 0.14.0

Here is a minimalist test case:

```python
import asyncio
import aiopg

from ddtrace import patch

patch(aiopg=True)


async def main():
    async with aiopg.connect(host=None) as db:
        pass

    while True:
        await asyncio.sleep(0.1)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

This logs the following error:
```
failed_to_send services to Agent: HTTP error status 400, reason Bad Request, message Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 18 Jun 2018 15:25:18 GMT
Content-Length: 59
```

And then `trace-agent` reports:
```
trace-agent[4437]: 2018-06-18 15:31:16 ERROR (receiver.go:275) - cannot decode v0.3 services payload: msgp: attempted to decode type "nil" with method for "str"
```

I believe this is related to https://github.com/DataDog/datadog-trace-agent/issues/350.

**Comment by palazzem** [comment] 2018-07-03 11:51
Hello @k4nar ! this error seems related to the services payload that is deprecated and is going to be removed in Tracer 1.0. It seems a bug in one of our integrations that is still using it but it doesn't affect tracing reporting. Did you test the latest version of our tracer? https://github.com/DataDog/dd-trace-py/releases/tag/v0.12.1

If yes, can you list the integrations you're using? Probably we need to update them as we did for others (https://github.com/DataDog/dd-trace-py/pull/468)

Thanks for reporting!

**Comment by k4nar** [comment] 2018-07-03 13:10
Thanks for the response :) .

In the test I've provided it happens with dd-trace-py 0.12.1 and with only the `aiopg` integration enabled.

**Comment by palazzem** [comment] 2018-07-03 13:11
OK I think the problem is the same as the other one. Let me check the `aiopg` integration so I can provide you a quick branch to test.

**Comment by palazzem** [comment] 2018-07-03 13:21
@k4nar can you check https://github.com/DataDog/dd-trace-py/pull/507 if it solves the problem? In that case I'll be sure it gets merged on `master` for the next 0.12.2 release.

**Comment by k4nar** [comment] 2018-07-03 16:10
I can confirm #507 fixes the error :+1: . Thanks!

**Comment by palazzem** [comment] 2018-07-03 16:12
Wonderful! fixing the CI build (not related to this PR) and merging the code into `master`! thanks for the quick feedback!

**Comment by palazzem** [comment] 2018-07-04 08:09
@k4nar done! It will be part of the 0.12.2 release.

**Closed** 2018-07-04 08:08 UTC
