### ISSUE TITLE
AttributeError on import with dd-trace-py>0.41.2

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [DataDog/dd-trace-py#2185] opened 2021-03-17 14:45 UTC
### Which version of dd-trace-py are you using?
dd-trace==0.47.0

### Which version of the libraries are you using?
connexion==2.5.1

You can copy/paste the output of `pip freeze` here.
`acme==0.39.0
aiohttp==3.6.2
aiohttp-jinja2==1.2.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.3.0
blinker==1.4
boto3==1.9.253
botocore==1.12.253
certbot==0.39.0
certifi==2019.9.11
cffi==1.13.1
chardet==3.0.4
click==6.6
clickclick==1.2.2
colorama==0.3.7
ConfigArgParse==0.15.1
configobj==5.0.6
connexion==2.5.1
cryptography==2.8
ddtrace==0.47.0
distro==1.4.0
docker==4.2.0
docutils==0.15.2
ecdsa==0.15
Flask==1.1.1
future==0.18.1
idna==2.8
importlib-metadata==0.23
inflection==0.3.1
intervaltree==3.1.0
itsdangerous==1.1.0
javaobj-py3==0.3.0
Jinja2==2.11.1
jmespath==0.9.4
jose==1.0.0
josepy==1.2.0
json5==0.8.5
jsonschema==3.2.0
mangopaysdk==3.7.0
MarkupSafe==1.1.1
mock==3.0.5
more-itertools==7.2.0
multidict==4.7.5
numpy==1.18.4
openapi-spec-validator==0.2.8
ovh==0.4.5
ovhcli==0.0.1
packaging==19.2
pandas==0.25.3
parsedatetime==2.4
pluggy==0.13.1
protobuf==3.15.6
psycopg2==2.8.4
py==1.8.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycparser==2.19
pycryptodomex==3.9.1
pyjks==19.0.0
PyJWT==1.7.1
pyOpenSSL==19.0.0
pyparsing==2.4.5
pypiwin32==223
pyRFC3339==1.1
pyrsistent==0.15.7
pytest==5.3.0
python-consul2==0.0.7
python-dateutil==2.8.1
python-hosts==1.0.1
python-jose==3.1.0
pytz==2019.3
pywin32==225
PyYAML==5.1.2
requests==2.23.0
requests-toolbelt==0.9.1
rsa==4.0
ruamel.yaml==0.16.5
ruamel.yaml.clib==0.2.0
s3transfer==0.2.1
sentry-sdk==0.15.1
simplejson==3.17.0
six==1.15.0
sortedcontainers==2.3.0
tenacity==7.0.0
terminaltables==3.0.0
twofish==0.3.0
urllib3==1.25.6
wcwidth==0.1.7
websocket-client==0.57.0
Werkzeug==0.16.0
wget==3.2
win-inet-pton==1.1.0
yarl==1.4.2
zipp==0.6.0
zope.component==4.5
zope.deferredimport==4.3.1
zope.deprecation==4.4.0
zope.event==4.4
zope.hookable==4.2.0
zope.interface==4.6.0
zope.proxy==4.3.2`

### How can we reproduce your problem?
Just run : 
`import connexion`

### What is the result that you get?
`Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import connexion
  File "C:\Python37\lib\site-packages\connexion\__init__.py", line 40, in <module>
    from .apis.aiohttp_api import AioHttpApi
  File "C:\Python37\lib\site-packages\connexion\apis\aiohttp_api.py", line 9, in <module>
    import aiohttp_jinja2
  File "C:\Python37\lib\site-packages\aiohttp_jinja2\__init__.py", line 7, in <module>
    from aiohttp import web
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\importer.py", line 157, in load_module
    notify_module_loaded(module)
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\decorators.py", line 445, in _synchronized
    return wrapped(*args, **kwargs)
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\importer.py", line 135, in notify_module_loaded
    hook(module)
  File "C:\Python37\lib\site-packages\ddtrace\monkey.py", line 105, in on_import
    imported_module.patch()
  File "C:\Python37\lib\site-packages\ddtrace\contrib\aiohttp\patch.py", line 29, in patch
    _w('aiohttp_jinja2', 'render_template', _trace_render_template)
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\wrappers.py", line 831, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\wrappers.py", line 777, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\wrappers.py", line 765, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "C:\Python37\lib\site-packages\ddtrace\vendor\wrapt\wrappers.py", line 763, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: module 'aiohttp_jinja2' has no attribute 'render_template'`

### What is the result that you expected?
No error.

Important note : The bug was not here in version 0.41.2.
It appeared since 0.42.0.

**Comment by Yun-Kim** [comment] 2021-04-28 20:11
Hi @LeComptoirDesPharmacies, thanks for reporting this issue. 

Unfortunately I wasn't able to reproduce your issue by installing your listed dependencies and by importing `connexion`, could you also tell me what version of Python you're running and let me know if you still are running into this issue?

**Comment by Kyle-Verhoog** [comment] 2021-07-27 19:52
Closing this out due to age - please reopen if you're still seeing the issue @LeComptoirDesPharmacies!

**Closed by Kyle-Verhoog** 2021-07-27 19:52 UTC

**Comment by LeComptoirDesPharmacies** [comment] 2021-08-02 16:10
We updated "Connexion" to version 2.9.0 and it seems to work, thanks !
We will inform you if error come back.
