### ISSUE TITLE
Psycopg patching doesn't properly handle execute_values

### ISSUE THREAD

**Issue by jfalkenstein** [DataDog/dd-trace-py#3115] opened 2022-01-07 17:36 UTC
The `execute_values` extension in psycopg2 composes and executes the query with b-string, even if you passed the query as a string. Below is the full function from psycopg2.extras

```python
def execute_values(cur, sql, argslist, template=None, page_size=100, fetch=False):
    from psycopg2.sql import Composable
    if isinstance(sql, Composable):
        sql = sql.as_string(cur)

    # we can't just use sql % vals because vals is bytes: if sql is bytes
    # there will be some decoding error because of stupid codec used, and Py3
    # doesn't implement % on bytes.
    if not isinstance(sql, bytes):
        sql = sql.encode(_ext.encodings[cur.connection.encoding])
    pre, post = _split_sql(sql)

    result = [] if fetch else None
    for page in _paginate(argslist, page_size=page_size):
        if template is None:
            template = b'(' + b','.join([b'%s'] * len(page[0])) + b')'
        parts = pre[:]
        for args in page:
            parts.append(cur.mogrify(template, args))
            parts.append(b',')
        parts[-1:] = post
        cur.execute(b''.join(parts))
        if fetch:
            result.extend(cur.fetchall())

    return result
```

The problem is that ddtrace assumes that the "resource" added to a span is a string. The result is that when `span.finish()` is called in the datadog lambda handler and it tries to serialize the span to json, it blows up with "TypeError: Object of type bytes is not JSON serializable".  Upon investigation, I discovered that the ddtrace.internal.encoder.py's JSONEncoder just does a simple json.dumps() on all the spans and the `resource` attribute on the span from the using `execute_values` is bytes, not a string.

I think the solution here is simply to update the Psycopg2TracedCursor class to decode the resource from bytes if it is bytes, like this:

```python
class Psycopg2TracedCursor(dbapi.TracedCursor):
    """TracedCursor for psycopg2"""

    def _trace_method(self, method, name, resource, extra_tags, *args, **kwargs):
        # treat psycopg2.sql.Composable resource objects as strings
        if isinstance(resource, Composable):
            resource = resource.as_string(self.__wrapped__)
        # THIS IS THE NEW PART BELOW (next 2 lines)
        if isinstance(resource, bytes):
            resource = resource.decode('utf-8')
        return super(Psycopg2TracedCursor, self)._trace_method(method, name, resource, extra_tags, *args, **kwargs)
```

### Which version of dd-trace-py are you using?
Lambda layer, v50.
### Which version of pip are you using?
n/a

### How can we reproduce your problem?
Use `execute_values` while inside a tracing context. It should have a 100% failure rate.

### What is the result that you get?
A type error when span.finish() is called and the metrics are furnished to DD.

### What is the result that you expected?
It should work as normal, with the resource decoded as a string.

**Comment by brettlangdon** [comment] 2022-01-07 19:23
Hey @jfalkenstein thanks for reporting this bug.

I have been looking into this, and it seems the issue is with the `LogWriter` we use with the Lambda layer since it encodes the span as JSON, where using the tracer with the Datadog agent will use msgpack which properly supports `bytes`.

My viewpoint right now is that we should fix the JSON encoder we use instead of putting a fix just in the psycopg2 integration since we could have the same issue with other integrations as well.


I'll work on putting a test case / fix for this together.

**Comment by jfalkenstein** [comment] 2022-01-07 19:40
That would be awesome! I wasn't sure how much traction this would get. 

For those watching this issue, until a fix is released, here is how I've worked around this issue:

```python

class TraceableCursorWrapper:

    def __init__(self, inner_cursor: Cursor):
        self._inner = inner_cursor

    def __getattr__(self, item):
        return getattr(self._inner, item)

    def __setattr__(self, key, value):
        if key == '_inner':
            setattr(self, key, value)
        setattr(self._inner, key, value)

    def execute(self, query, vars=None):
        if isinstance(query, bytes):
            query = query.decode('utf-8')
        return self._inner.execute(query, vars)


def execute_values(
    cur: Cursor,
    sql: str,
    argslist: list[tuple],
    fetch: bool = False,
    template: str = None,
    page_size: int = 100,
):
    traceable_cursor = TraceableCursorWrapper(cur)

    return pg_execute_values(
        cur=traceable_cursor,
        sql=sql,
        argslist=argslist,
        fetch=fetch,
        template=template,
        page_size=page_size
    )
```

It's a bit ugly, but it does the trick for now.

**Comment by brettlangdon** [comment] 2022-01-07 20:13
@jfalkenstein I have opened #3117 to address this issue.

**Closed** 2022-01-25 22:06 UTC
