### ISSUE TITLE
Can't start celery with ddtrace and gevent

### ISSUE THREAD

**Issue by johnnymetz** [DataDog/dd-trace-py#5453] opened 2023-03-31 19:27 UTC
### Summary of problem

The following celery startup command errors out:

```
ddtrace-run celery -A mysite.celery.app worker --pool=gevent
```

Note, this may be related to https://github.com/DataDog/dd-trace-py/issues/5344

### Which version of dd-trace-py are you using?

1.10.2

### Which version of pip are you using?

23.0.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
amqp==5.1.1
asgiref==3.6.0
async-timeout==4.0.2
attrs==22.2.0
billiard==3.6.4.0
bytecode==0.14.0
cattrs==22.2.0
celery==5.2.7
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
ddsketch==2.0.4
ddtrace==1.10.2
Django==4.1.7
django-environ==0.10.0
django-extensions==3.2.1
envier==0.4.0
gevent==22.10.2
greenlet==2.0.2
jsonschema==4.17.3
kombu==5.2.4
packaging==23.0
prompt-toolkit==3.0.38
protobuf==4.22.1
pyrsistent==0.19.3
pytz==2023.3
redis==4.5.4
six==1.16.0
sqlparse==0.4.3
tenacity==8.2.2
typing_extensions==4.5.0
vine==5.0.0
wcwidth==0.2.6
xmltodict==0.13.0
zope.event==4.6
zope.interface==6.0
</details>

### How can we reproduce your problem?

Example project (directions to reproduce in README.md): https://github.com/johnnymetz/ddtrace-celery-gevent-bug

Demo video: https://www.loom.com/share/0d2b49c6f7284672a149182094ffef07

### What is the result that you get?

Celery worker fails to start.

### What is the result that you expected?

Celery worker starts and successfully processes tasks.

**Comment by johnnymetz** [comment] 2023-03-31 19:28
Note, we shouldn't have to set `DJANGO_SETTINGS_MODULE`. This is set for us in the celery startup script [here](https://github.com/johnnymetz/ddtrace-celery-gevent-bug/blob/main/mysite/celery.py#L10).

**Comment by P403n1x87** [comment] 2023-04-01 10:28
@johnnymetz thanks for reporting this! Indeed I have observed this and in my tests with celery I have used
~~~
PYTHONPATH=. ddtrace-run celery -A proj worker --pool=gevent --concurrency=25 --loglevel=info
~~~
as launch command (note the `PYTHONPATH=.`). I also have `export DJANGO_SETTINGS_MODULE="proj.settings"`. I did not realise that these are not required when running without `gevent` or `ddtrace-run`. I'll look into it.

**Comment by P403n1x87** [comment] 2023-04-01 11:14
From a preliminary investigation, this seems to be due to a combination of the new module cleanup introduced in 1.9.3 to improve compatibility with gevent and side effects caused by eager imports in the Django integration. Unfortunately, another bug currently prevents the Django integration from being disabled, but I can confirm that disabling the Django integration seems to solve this. I'm looking into ways of reducing the side effects caused by it as a fix for this.

Another way of making the launch command succeed is to set `DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=0`, but there are chances that the application won't work as expected.

**Comment by johnnymetz** [comment] 2023-04-28 14:58
Hi @P403n1x87 any update on this?

**Comment by P403n1x87** [comment] 2023-05-02 15:42
@johnnymetz the PR linked above is now in a state whereby we fix the issue while maintaining the existing Django tracing functionalities. In theory, this should also fix #5344. We hope to have this merged soon, but in the meantime feel free to test the PR itself if you can. Thanks for your help and patience 🙏

**Closed** 2023-05-05 09:15 UTC
Labels: Tracing

**Comment by ZStriker19** [comment] 2023-05-08 15:54
@johnnymetz  1.12.5 has just been cut, which contains Gab's PR mentioned above. Could you please see if it resolves your issue? https://github.com/DataDog/dd-trace-py/releases/tag/v1.12.5

**Comment by johnnymetz** [comment] 2023-05-09 00:51
Just confirmed `1.12.6` resolves the bug. Thanks!
