### ISSUE TITLE
1.6.0rc1 breaks my Heroku environment

### ISSUE THREAD

**Issue by tolomea** [DataDog/dd-trace-py#4352] opened 2022-10-21 09:01 UTC
Sorry about the limited info here.

It works fine on 1.5.0 and local test with 1.6.0. 

I'm not sure how it broke the Heroku environment as it took Sentry down with it.
Heroku says it deployed and started up fine but every request 500's and nothing makes it to Sentry.
Unfortunately I didn't grab the logs and I can't afford the time to dig into this further.
Also the agent is largely disabled in this environment.

Relevant env
DD_TRACE_ENABLED = false
DISABLE_DATADOG_AGENT = true

Server run command
ddtrace-run gunicorn --access-logfile /app/access.log eligible.wsgi

Version info
Python 3.10.6
Django 3.2.16

ddtrace==1.6.0rc1
  - attrs [required: >=20, installed: 22.1.0]
  - bytecode [required: Any, installed: 0.13.0]
  - cattrs [required: Any, installed: 22.2.0]
    - attrs [required: >=20, installed: 22.1.0]
    - exceptiongroup [required: Any, installed: 1.0.0rc9]
  - ddsketch [required: >=2.0.1, installed: 2.0.4]
    - protobuf [required: >=3.0.0, installed: 4.21.8]
    - six [required: Any, installed: 1.16.0]
  - envier [required: Any, installed: 0.4.0]
  - forbiddenfruit [required: >=0.1.4, installed: 0.1.4]
  - jsonschema [required: Any, installed: 4.16.0]
    - attrs [required: >=17.4.0, installed: 22.1.0]
    - pyrsistent [required: >=0.14.0,!=0.17.2,!=0.17.1,!=0.17.0, installed: 0.18.1]
  - packaging [required: >=17.1, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - protobuf [required: >=3, installed: 4.21.8]
  - six [required: >=1.12.0, installed: 1.16.0]
  - tenacity [required: >=5, installed: 8.1.0]
  - typing-extensions [required: Any, installed: 4.4.0]
  - xmltodict [required: >=0.12, installed: 0.13.0]

**Comment by Yun-Kim** [comment] 2022-10-21 17:48
Hi @tolomea, could you please include logs or steps to reproduce this? Thanks!

**Comment by Yun-Kim** [comment] 2022-10-26 20:29
Just to follow up, I'm not able to reproduce the errors you mentioned with the information you've provided. Could you also include logs/reproduction steps? Might be worth noting that we currently haven't officially released 1.6.0 and don't ship wheels for it yet, so it could be a build error.

**Comment by Yun-Kim** [comment] 2022-11-01 14:44
@tolomea we still haven't been able to reproduce this error so we're closing this issue. If you're still experiencing this problem after we publish wheels for version 1.6.0 feel free to reopen this issue.

**Closed by Yun-Kim** 2022-11-01 14:44 UTC
