### ISSUE TITLE
Infinite loop with aiohttp and debug logging

### ISSUE THREAD

**Issue by juzna** [DataDog/dd-trace-py#1003] opened 2019-07-26 09:07 UTC
If I enable [tracing for aiohttp web app](http://pypi.datadoghq.com/trace/docs/web_integrations.html#aiohttp) and also [propagate trace ids to logs](https://docs.datadoghq.com/tracing/advanced/connect_logs_and_traces/?tab=python), I get an infinite loop at the app startup.

This only happens with debug log level. The reason is explained below.

The loop is as follows:
 1. `aiohttp.web.run_app` creates a new event loop
 2. `BaseSelectorEventLoop` calls `logger.debug(...)` in constructor
 3. logger tries to add trace ids by calling ddtrace `get_correlation_ids`
 4. this gets current context via `aiohttp` context provider
 5. the context provider calls `asyncio.get_event_loop()`; because no loop has been created yet, it creates a new event loop, going to step 2 and starting the loop

Repro case
```py
import logging
import sys

from aiohttp import web

from ddtrace import patch, tracer
from ddtrace.contrib.aiohttp import trace_app

patch(logging=True) # this adds datadog trace ids to logs

logging.basicConfig(
    stream=sys.stdout,
    level="DEBUG", # debug logs need to be on to trigger the issue
)

app = web.Application()
trace_app(app, tracer, service='ping')
web.run_app(app, host="0.0.0.0", port=8080) # triggers the loop
```

Dependencies: `pip install aiohttp ddtrace`

Versions of dependencies:
```
$ pip freeze
aiohttp==3.5.4
async-timeout==3.0.1
attrs==19.1.0
chardet==3.0.4
ddtrace==0.27.1
idna==2.8
multidict==4.5.2
psutil==5.6.3
yarl==1.3.0
```

Tested on Mac OS X 10.14.3 with Python 3.7.4.

**Comment by brettlangdon** [comment] 2019-07-29 12:49
@juzna thank you for reporting this and for a the reproduction case. We'll work on scheduling time for someone to dig into this.

**Comment by alesveselka** [comment] 2019-09-23 13:30
Hi, any news regarding this issue? I'd really like this to be fixed!

**Comment by majorgreys** [comment] 2020-04-06 20:52
@juzna @alesveselka We are sorry for not updating this issue sooner. 

@zhammer's recent fix for a related issue brought this issue up again. However, the issue here is not a deadlock caused by library internal logging. 

Instead, the infinite loop appears that this issue was resolved by the new contextvars-based tracer for Python 3.7 added in 0.29.0 which does not repeatedly call the `BaseSelectorEventLoop` constructor.

I have shared my code here:

https://gist.github.com/majorgreys/3d19d322b5fe163d56deab448a6045ab

One thing I did notice was that though I saw `DEBUG:asyncio:Using selector: EpollSelector` repeated in the logs, it did not go on infinitely. I'm not sure why that is but will leave further investigation till we know this issue remains for `ddtrace>=0.29.0`.

**Closed by majorgreys** 2020-04-06 20:52 UTC
Labels: bug, community
