### ISSUE TITLE
Undefined symbol: rd_kafka_AclBinding_destroy on Python 3.11

### ISSUE THREAD

**Issue by maciejfic** [DataDog/dd-trace-py#4586] opened 2022-11-18 14:16 UTC
### Summary of problem
I'm trying to get ddtrace running on Python 3.11. To do that I've built custom wheel for `confluent-kafka`, but I'm getting error:
```
File "/home/user/venv/lib/python3.11/site-packages/ddtrace/internal/module.py", line 187, in _create_module
    return self.loader.create_module(spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/user/venv/lib/python3.11/site-packages/confluent_kafka/cimpl.cpython-311-x86_64-linux-gnu.so: undefined symbol: rd_kafka_AclBinding_destroy

Process finished with exit code 1
```

### Which version of dd-trace-py are you using?
Tried 1.6.1 and wheel build directly from master

### Which version of pip are you using?
22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  confluent-kafka=1.9.2 - custom built wheel from most recent master

  dd-trace=1.6.1
</details>

### How can we reproduce your problem?
Build most recent dd-trace on python 3.11

### What is the result that you get?
Error on django startup

### What is the result that you expected?
Django app starts normally without an error

**Comment by majorgreys** [comment] 2022-11-28 19:28
Was the behavior the same when installing from the published 1.6.1 wheel as it was with installing from source? To make sure we are comparing the same code, can you build the wheel from the tag `v1.6.1`? Can you also confirm that the behavior without the ddtrace is what you expect?

**Comment by maxvwolff** [comment] 2023-02-19 06:03
Any updates here? Experiencing the same issue.

**Comment by P403n1x87** [comment] 2023-02-23 23:22
@maxvwolff could you share some minimal list of steps to reproduce the issue?

**Comment by P403n1x87** [comment] 2023-02-23 23:58
I've managed to compile confluent-kafka from sources but this is what I get
~~~
(kafka) lima@lima-ubuntu:/tmp/kafka/librdkafka$ python -c 'import confluent_kafka; print(confluent_kafka.version())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/kafka/lib/python3.11/site-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/tmp/kafka/lib/python3.11/site-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
ImportError: /tmp/kafka/lib/python3.11/site-packages/confluent_kafka/cimpl.cpython-311-aarch64-linux-gnu.so: undefined symbol: rd_kafka_event_AlterConsumerGroupOffsets_result
(kafka) lima@lima-ubuntu:/tmp/kafka/librdkafka$ ddtrace-run python -c 'import confluent_kafka; print(confluent_kafka.version())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/kafka/lib/python3.11/site-packages/ddtrace/internal/module.py", line 192, in _exec_module
    self.loader.exec_module(module)
  File "/tmp/kafka/lib/python3.11/site-packages/confluent_kafka/__init__.py", line 19, in <module>
    from .deserializing_consumer import DeserializingConsumer
  File "/tmp/kafka/lib/python3.11/site-packages/ddtrace/internal/module.py", line 192, in _exec_module
    self.loader.exec_module(module)
  File "/tmp/kafka/lib/python3.11/site-packages/confluent_kafka/deserializing_consumer.py", line 19, in <module>
    from confluent_kafka.cimpl import Consumer as _ConsumerImpl
  File "/tmp/kafka/lib/python3.11/site-packages/ddtrace/internal/module.py", line 189, in _create_module
    return self.loader.create_module(spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /tmp/kafka/lib/python3.11/site-packages/confluent_kafka/cimpl.cpython-311-aarch64-linux-gnu.so: undefined symbol: rd_kafka_event_AlterConsumerGroupOffsets_result
~~~
so it doesn't look like we are causing the issue.

**Comment by maxvwolff** [comment] 2023-02-24 02:18
Looks like it was a build issue. The remote setup I used to compile the Docker image was using a different arm architecture than my local setup. So when I rebuilt it locally it didn't throw the error anymore.

**Comment by P403n1x87** [comment] 2023-02-24 09:50
Thanks for confirming @maxvwolff. I'm closing this issue as this likely a compilation issue with the `confluent-kafka` library.

**Closed by P403n1x87** 2023-02-24 09:50 UTC
