### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by adamchainz** [DataDog/dd-trace-py#1128] opened 2019-11-11 16:11 UTC
I can't find a changelog so I'm not sure if it's safe to upgrade to a new version, if it's still compatible with the libraries I want to trace.

**Comment by brettlangdon** [comment] 2019-11-11 17:42
Hey @adamchainz we publish our release notes in https://github.com/DataDog/dd-trace-py/releases

**Comment by brettlangdon** [comment] 2019-11-11 17:43
Duplicate of #1056, will close this and we can track together over there.

**Closed by brettlangdon** 2019-11-11 17:43 UTC
