### ISSUE TITLE
inject_trace_to_kinesis_stream fails with TypeError

### ISSUE THREAD

**Issue by mzizzi-patreon** [DataDog/dd-trace-py#5255] opened 2023-03-02 19:03 UTC
edit: looks like a dupe of: https://github.com/DataDog/dd-trace-py/issues/5236

### Summary of problem

Injecting trace context into certain kinesis messages fails with type-error.

```
Traceback (most recent call last):
  File \"...site-packages/ddtrace/contrib/botocore/patch.py\", line 351, in patched_api_call
    inject_trace_to_kinesis_stream(params, span)
  File \"...site-packages/ddtrace/contrib/botocore/patch.py\", line 267, in inject_trace_to_kinesis_stream
    inject_trace_to_kinesis_stream_data(record, span)
  File \"...site-packages/ddtrace/contrib/botocore/patch.py\", line 233, in inject_trace_to_kinesis_stream_data
    line_break, data_obj = get_kinesis_data_object(data)
  File \"...site-packages/ddtrace/contrib/botocore/patch.py\", line 206, in get_kinesis_data_object
    return get_json_from_str(data)
  File \"...site-packages/ddtrace/contrib/botocore/patch.py\", line 187, in get_json_from_str
    if data_str.endswith(LINE_BREAK):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

We experienced this issue when upgrading from from ddtrace 1.6.3 -> 1.9.0

https://github.com/DataDog/dd-trace-py/pull/4700 added logic to check for newlines. this can fail if the input type isn't a string:
https://github.com/DataDog/dd-trace-py/pull/4700/files#diff-853d8228116e3efbb7a697d71951ab7680ecb68ee5567a1d1c58f3952f8fb42fR186

### Which version of dd-trace-py are you using?
```
ddtrace==1.9.0
```

### Which libraries and their versions are you using?
```
botocore==1.25.2
boto3==1.22.2
```

### What is the result that you get?
Errors injecting trace context.

### What is the result that you expected?
Patched kinesis client injects trace context.

**Comment by adamantike** [comment] 2023-03-03 13:38
This has been also reported in #5236

**Comment by mabdinur** [comment] 2023-03-13 13:33
Duplicate of: https://github.com/DataDog/dd-trace-py/issues/5236

**Closed by mabdinur** 2023-03-13 13:33 UTC
Labels: bug
