### ISSUE TITLE
2.7.5+ makes application crash because of kafka Consumer.consumer instrumentation

### ISSUE THREAD

**Issue by JulienFS** [DataDog/dd-trace-py#8873] opened 2024-04-04 14:42 UTC
### Summary of problem

Auto-instrumentation of kafka crashes when consumer.Consume returns no message

### Which version of dd-trace-py are you using?

2.7.6

### Which version of pip are you using?
24.0

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?

Install version 2.7.5 or 2.7.6, enable auto-instrumentation, use confluent-kafka-python with the method Consume and a timeout. Consume must return no message.

### What is the result that you get?

```
  File "/home/dude/.local/lib/python3.11/site-packages/ddtrace/contrib/kafka/patch.py", line 237, in _instrument_message
    first_message = messages[0]
                    ~~~~~~~~^^^
IndexError: list index out of range
```

### What is the result that you expected?

No crash

### Context

Introduced here : https://github.com/DataDog/dd-trace-py/pull/8511
Introduced to 2.7 here : https://github.com/DataDog/dd-trace-py/pull/8757

Problematic line is here : https://github.com/DataDog/dd-trace-py/blame/647b07472c583c10d1cee52b9f518ea61237c720/ddtrace/contrib/kafka/patch.py#L228
`result` can be empty, a check needs to be done.

**Comment by emmettbutler** [comment] 2024-04-04 16:27
Thanks for the report, @JulienFS. It appears to be a duplicate of #8846, which there's a fix under review for.

**Closed** 2024-04-04 16:28 UTC
