### ISSUE TITLE
Celery Retry exceptions are noisy errors

### ISSUE THREAD

**Issue by stevepeak** [DataDog/dd-trace-py#603] opened 2018-09-13 08:14 UTC
Our service has frequent Celery Retry exceptions raised. Datadog reports these as errors which make sit very noisy and hard to find "real" errors.

Any suggestions on how to change an exception from Error to warning or ignore it entirely?

**Comment by Kyle-Verhoog** [comment] 2018-09-14 20:34
Hi @stevepeak,

We're aware that this is an issue and it will be addressed in our upcoming 0.15 release.

Thanks!

**Comment by Kyle-Verhoog** [comment] 2018-09-26 14:07
Hi @stevepeak,

We're circling back to this issue to include a fix in our upcoming release. Can you provide more information about how you are retrying your tasks?

**Comment by brettlangdon** [comment] 2019-09-03 20:01
Closing this issue for now because of the silence, but @stevepeak if you are still having this problem, please let us know and we'd love to how you are retrying the tasks so we can reproduce and resolve on our end.

**Closed by brettlangdon** 2019-09-03 20:01 UTC
Labels: enhancement

**Comment by patrickkidd** [comment] 2022-01-06 20:57
I would also love to hear about a way to ignore celery retry errors in DD.
