### ISSUE TITLE
ddtrace 2.0.0 fails with openai 0.28.1

### ISSUE THREAD

**Issue by iherasymenko** [DataDog/dd-trace-py#7144] opened 2023-10-03 19:49 UTC
### Summary of problem

```
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/internal/module.py", line 220, in _exec_module
    self.loader.exec_module(module)
  File "<redacted>/<redacted>.py", line 4, in <module>
    import openai
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<redacted>/<redacted>/lib/python3.11/site-packages/wrapt/importer.py", line 183, in _exec_module
    notify_module_loaded(module)
  File "<redacted>/<redacted>/lib/python3.11/site-packages/wrapt/importer.py", line 116, in notify_module_loaded
    hook(module)
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/_monkey.py", line 167, in on_import
    imported_module.patch()
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/contrib/openai/patch.py", line 160, in patch
    wrap(openai.util.convert_to_openai_object, _patched_convert(openai, integration))
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/internal/wrapping/__init__.py", line 229, in wrap
    code = wrap_bytecode(wrapper, wrapped)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/internal/wrapping/__init__.py", line 142, in wrap_bytecode
    instrs[0:0] = [Instr("MAKE_CELL", CellVar(_), lineno=lineno) for _ in code.co_cellvars]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/<redacted>/lib/python3.11/site-packages/ddtrace/internal/wrapping/__init__.py", line 142, in <listcomp>
    instrs[0:0] = [Instr("MAKE_CELL", CellVar(_), lineno=lineno) for _ in code.co_cellvars]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>/<redacted>/lib/python3.11/site-packages/bytecode/instr.py", line 534, in __init__
    self._set(name, arg)
  File "<redacted>/<redacted>/lib/python3.11/site-packages/bytecode/instr.py", line 737, in _set
    self._check_arg(name, opcode, arg)
  File "<redacted>/<redacted>/lib/python3.11/site-packages/bytecode/instr.py", line 801, in _check_arg
    raise TypeError(
TypeError: operation MAKE_CELL argument must be CellVar or FreeVar, got CellVar


```

<details>
  <summary>pip freeze</summary>
<code>aiohttp==3.8.5
aiosignal==1.3.1
amqp==5.1.1
apispec==6.3.0
apispec-webframeworks==0.5.2
async-timeout==4.0.3
attrs==23.1.0
authy==2.2.6
bcrypt==4.0.1
beautifulsoup4==4.12.2
billiard==4.1.0
black==23.9.1
bleach==6.0.0
bleach-allowlist==1.0.3
blinker==1.6.2
boto3==1.28.58
botocore==1.31.58
bytecode==0.15.0
cachetools==5.3.1
cattrs==23.1.2
celery==5.3.0
certifi==2023.7.22
cffi==1.16.0
cfgv==3.4.0
chardet==5.2.0
charset-normalizer==3.3.0
click==8.1.7
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
contextlib2==21.6.0
coverage==7.3.2
cryptography==41.0.4
cssselect==1.2.0
cssutils==2.7.1
datadog==0.47.0
ddsketch==2.0.4
ddtrace==2.0.0
debugpy==1.8.0
defusedxml==0.7.1
Deprecated==1.2.14
deptry==0.12.0
distlib==0.3.7
dnspython==1.16.0
elastic-site-search==2.1.1
elasticsearch==7.13.4
envier==0.4.0
expiringdict==1.2.2
feedfinder2==0.0.4
feedparser==6.0.10
filelock==3.12.4
Flask==2.3.3
Flask-Cors==3.0.9
Flask-JWT-Extended==4.3.1
Flask-Limiter==2.0.4
Flask-Pydantic==0.9.0
freezegun==1.2.2
frozenlist==1.4.0
gevent==23.9.1
google-api-core==2.12.0
google-auth==2.23.2
google-cloud-core==2.3.3
google-cloud-translate==3.12.0
googleapis-common-protos==1.60.0
greenlet==3.0.0
grpcio==1.59.0
grpcio-status==1.59.0
gunicorn==21.2.0
identify==2.5.30
idna==3.4
ImageHash==4.3.1
importlib-metadata==6.8.0
importlib-resources==6.1.0
iniconfig==2.0.0
itsdangerous==2.1.2
jieba3k==0.35.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
kombu==5.3.2
launchdarkly-server-sdk==8.1.6
limits==3.6.0
lxml==4.9.3
Markdown==3.4.4
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-dataclass==8.5.14
marshmallow-mongoengine==0.30.2
mongoengine==0.21.0
multidict==6.0.4
mypy==1.5.1
mypy-extensions==1.0.0
ndg-httpsclient==0.5.1
newspaper3k==0.2.8
nltk==3.8.1
nodeenv==1.8.0
numpy==1.26.0
oauthlib==3.1.0
openai==0.28.1
opentelemetry-api==1.20.0
packaging==23.2
pandas==2.1.1
pathspec==0.11.2
phonenumbers==8.13.22
Pillow==10.0.1
platformdirs==3.11.0
pluggy==0.13.1
pre-commit==3.4.0
premailer==3.10.0
prompt-toolkit==3.0.39
proto-plus==1.22.3
protobuf==4.24.3
psutil==5.6.7
psycopg2-binary==2.9.9
pusher==3.3.2
pyap==0.3.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pybreaker==1.0.2
pycparser==2.21
pycryptodome==3.19.0
pydantic==1.9.0
PyJWT==2.8.0
pymongo==3.12.0
PyNaCl==1.5.0
pyOpenSSL==23.2.0
pyRFC3339==1.1
pytest==7.4.2
pytest-cov==4.1.0
pytest-env==1.0.1
pytest-mock==3.11.1
pytest-order==1.1.0
pytest-socket==0.6.0
pytest-split==0.8.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-http-client==3.3.7
python-json-logger==2.0.7
python-redis-lock==4.0.0
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
rapidfuzz==3.3.1
redis==4.5.4
regex==2023.10.3
requests==2.31.0
requests-aws4auth==1.2.3
requests-file==1.5.1
requests-mock==1.11.0
rsa==4.9
s3transfer==0.7.0
schema==0.7.5
scipy==1.11.3
semver==3.0.1
sendgrid==6.10.0
sentry-sdk==1.31.0
sgmllib3k==1.0.0
six==1.16.0
smooch==5.20.0
soupsieve==2.5
SQLAlchemy==1.3.3
starkbank-ecdsa==2.2.0
tenacity==8.2.3
tinysegmenter==0.3
tld==0.13
tldextract==3.6.0
tqdm==4.66.1
twilio==6.35.1
types-bleach==6.0.0.4
types-cachetools==5.3.0.6
types-Markdown==3.4.2.10
types-pyOpenSSL==23.2.0.2
types-python-dateutil==2.8.19.14
types-pytz==2023.3.1.1
types-redis==4.5.4.1
types-requests==2.31.0.6
types-urllib3==1.26.25.14
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
unicodecsv==0.14.1
Unidecode==1.3.7
urllib3==1.26.17
validators==0.22.0
vcrpy==5.1.0
vine==5.0.0
virtualenv==20.24.5
watchdog==3.0.0
wcwidth==0.2.8
webencodings==0.5.1
Werkzeug==2.3.7
wrapt==1.15.0
XlsxWriter==3.1.6
xmltodict==0.13.0
yarl==1.9.2
zenpy==2.0.25
zipp==3.17.0
zope.event==5.0
zope.interface==6.0
</code>
</details>

```
ddtrace-run gunicorn app:app -b 0.0.0.0:8000 -w 1 --reload -k gevent --log-level info --capture-output --error-logfile -
```

**Comment by P403n1x87** [comment] 2023-10-04 08:45
@iherasymenko thanks for reporting this. Would you be able to check if setting the environment variable `DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE` to `0` fixes this issue? Please note that this might cause other issues with gevent, but knowing whether this issue is resolved this way will help us narrow down the root cause and produce the right fix for this problem.

**Comment by iherasymenko** [comment] 2023-10-04 14:47
@P403n1x87 Thank you for looking into this. Setting `DD_UNLOAD_MODULES_FROM_SITECUSTOMIZE=0` does fix the issue (i.e. the application starts normally).

**Closed** 2023-10-04 16:02 UTC
