### ISSUE TITLE
Critical error encountered with ddtrace patch and langchain.

### ISSUE THREAD

**Issue by scottberres-tr** [DataDog/dd-trace-py#7248] opened 2023-10-13 19:45 UTC
We started seeing an issue due to having to upgrade langchain. With version 0.0.300, the datadog patch_all() works correctly and the langchain is created. We had to upgrade to 0.0.306 and we encountered a Critical exception that crashes our python worker. 

<details>
Today I am getting an exception when dd is trying to wrap the object.

` File \".\\.venv\\lib\\site-packages\\ddtrace\\contrib\\langchain\\patch.py\", line 754, in patch
    wrap(\"langchain\", \"llms.base.BaseLLM.generate\", traced_llm_generate(langchain))
  File \".\\.venv\\lib\\site-packages\\ddtrace\\vendor\\wrapt\\wrappers.py\", line 882, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File \".\\.venv\\lib\\site-packages\\ddtrace\\vendor\\wrapt\\wrappers.py\", line 822, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File \".\\.venv\\lib\\site-packages\\ddtrace\\vendor\\wrapt\\wrappers.py\", line 808, in resolve_path
    original = lookup_attribute(parent, attribute)
  File \".\\.venv\\lib\\site-packages\\ddtrace\\vendor\\wrapt\\wrappers.py\", line 806, in lookup_attribute
    return getattr(parent, attribute)
  File \".\\.venv\\lib\\site-packages\\langchain\\__init__.py\", line 332, in __getattr__
    raise AttributeError(f\"Could not find: {name}\")
AttributeError: Could not find: llms`

This is happening on ddtrace 2.1.0 and all previous versions.
</details>

To reproduce this

`from ddtrace import patch_all
patch_all()`

Create any object that references langchain.

from langchain.prompts import PromptTemplate
from langchain.base_language import BaseLanguageModel
from langchain.prompts import FewShotPromptTemplate
from langchain.chains import LLMChain

With these imports I get the above error. If I got back to langchain .300, the application is able to successfully finish.

**Comment by rem-lag** [comment] 2023-10-13 20:42
I've been paying attention to this issue, the `2.0.3` release from earlier today looks like it has the fix and it looks like the PR to get the fix in `1.20.x` was just merged a bit ago too

all the PRs and stuff are linked from this earlier issue post
https://github.com/DataDog/dd-trace-py/issues/7123

**Comment by Yun-Kim** [comment] 2023-10-30 14:38
Hi @scottberres-tr, thanks for reaching out!

@rem-lag beat me to the punch - apologies for the late response. I attempted to reproduce your issue with `langchain==0.0.306` and `ddtrace==2.0.3`/`ddtrace==2.1.1`/`ddtrace==1.20.5` and it looks like this issue should be resolved by any of these ddtrace versions or later! Please let me know if you still have problems.

**Closed** 2023-11-06 14:16 UTC
