### ISSUE TITLE
Traces are getting lost with warning message "Writer queue is full has more than 1000 traces"

### ISSUE THREAD

**Issue by shuklaabhi** [DataDog/dd-trace-py#1701] opened 2020-10-01 13:09 UTC
We are running celery workers as ECS services in AWS. Each service has 3 containers:

- one container running celery worker
- one container for logrouter running image "amazon/aws-for-fluent-bit:2.3.1"
- one container for datadog agent running image "datadog/agent:7.20.2"

**We can see both logs and traces** in the datadog dashboard from the celery worker,  but the following warning in the DD logs keep popping up very frequently in logs.

> Writer queue is full has more than 1000 traces, some traces will be lost, N additional messages skipped

### Which version of dd-trace-py are you using?
ddtrace==0.42.0

DD tracer configuration emitted in the logs
```
{
    "date": "2020-10-02T10:25:39.927169",
    "os_name": "Linux",
    "os_version": "4.14.193-149.317.amzn2.x86_64",
    "is_64_bit": true,
    "architecture": "64bit",
    "vm": "CPython",
    "version": "0.42.0",
    "lang": "python",
    "lang_version": "3.6.10",
    "pip_version": "20.0.2",
    "in_virtual_env": false,
    "agent_url": "http://localhost:8126",
    "agent_error": null,
    "env": "",
    "is_global_tracer": false,
    "enabled_env_setting": null,
    "tracer_enabled": true,
    "sampler_type": "DatadogSampler",
    "priority_sampler_type": "RateByServiceSampler",
    "service": "",
    "debug": true,
    "enabled_cli": false,
    "analytics_enabled": false,
    "log_injection_enabled": false,
    "health_metrics_enabled": false,
    "dd_version": "",
    "priority_sampling_enabled": true,
    "global_tags": "",
    "tracer_tags": "",
    "integrations": {
      "asyncio": "N/A",
      "boto": "N/A",
      "botocore": {
        "enabled": true,
        "instrumented": false,
        "module_available": true,
        "module_version": "1.12.253",
        "module_imported": false,
        "config": "N/A"
      },
      "bottle": "N/A",
      "cassandra": "N/A",
      "celery": {
        "enabled": true,
        "instrumented": false,
        "module_available": true,
        "module_version": "4.2.0",
        "module_imported": true,
        "config": "N/A"
      },
      "consul": "N/A",
      "django": "N/A",
      "elasticsearch": "N/A",
      "algoliasearch": "N/A",
      "futures": "N/A",
      "grpc": "N/A",
      "mongoengine": "N/A",
      "mysql": "N/A",
      "mysqldb": "N/A",
      "pymysql": "N/A",
      "psycopg": "N/A",
      "pylibmc": "N/A",
      "pymemcache": "N/A",
      "pymongo": {
        "enabled": true,
        "instrumented": false,
        "module_available": true,
        "module_version": "3.4.0",
        "module_imported": false,
        "config": "N/A"
      },
      "redis": "N/A",
      "rediscluster": "N/A",
      "requests": {
        "enabled": true,
        "instrumented": false,
        "module_available": true,
        "module_version": "2.21.0",
        "module_imported": false,
        "config": "N/A"
      },
      "sqlalchemy": "N/A",
      "sqlite3": "N/A",
      "aiohttp": "N/A",
      "aiopg": "N/A",
      "aiobotocore": "N/A",
      "httplib": "N/A",
      "vertica": "N/A",
      "molten": "N/A",
      "jinja2": "N/A",
      "mako": "N/A",
      "flask": "N/A",
      "kombu": {
        "enabled": false,
        "instrumented": false,
        "module_available": true,
        "module_version": "4.6.11",
        "module_imported": true,
        "config": null
      },
      "falcon": "N/A",
      "pylons": "N/A",
      "pyramid": "N/A",
      "logging": "N/A"
    }
  }
```

### Which version of the libraries are you using?
celery==4.2.0

You can copy/paste the output of `pip freeze` here.

amqp==2.6.1
analytics-python==1.2.9
appdirs==1.4.4
appnope==0.1.0
arrow==0.14.2
attrs==20.1.0
awscli==1.18.133
backcall==0.2.0
bcrypt==3.1.4
billiard==3.5.0.4
black==19.10b0
blinker==1.4
boto3==1.9.218
botocore==1.12.253
celery==4.2.0
certifi==2020.6.20
cffi==1.14.2
cfgv==3.2.0
chardet==3.0.3
click==7.1.2
clickclick==1.2.2
colorama==0.4.3
connexion==2.2.0
cryptography==3.1
datadog==0.38.0
ddtrace==0.42.0
decorator==4.3.2
defusedxml==0.6.0
distlib==0.3.1
dnspython==1.16.0
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
Fabric==1.13.1
fabric2==2.4.0
filelock==3.0.12
flake8==3.7.9
flake8-import-order==0.18.1
Flask==1.0.2
Flask-Admin==1.5.3
Flask-Principal==0.4.0
flower==0.9.5
future==0.17.1
fuzzywuzzy==0.16.0
gitlint==0.13.1
httplib2==0.18.1
humanize==2.6.0
identify==1.4.30
idna==2.8
importlib-metadata==1.7.0
importlib-resources==3.0.0
inflection==0.5.1
intervaltree==3.1.0
invoke==1.2.0
ipython==7.16.1
ipython-genutils==0.2.0
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.17.2
Jinja2==2.11.2
jira==2.0.0
jmespath==0.10.0
JSON-log-formatter==0.3.0
jsonschema==2.6.0
kombu==4.6.11
lxml==3.8.0
MarkupSafe==1.1.1
mccabe==0.6.1
mock==3.0.5
msgpack==1.0.0
mysql-connector-python==8.0.19
nodeenv==1.5.0
numpy==1.12.1
oauth2==1.9.0.post1
oauthlib==3.1.0
openapi-spec-validator==0.2.7
openexchangerates3==0.1.1
openpyxl==3.0.3
paramiko==2.4.2
parso==0.7.1
pathspec==0.8.0
pbr==5.5.0
pexpect==4.8.0
pg8000==1.12.4
pickleshare==0.7.5
prance==0.15.0
pre-commit==2.2.0
prometheus-client==0.8.0
prompt-toolkit==3.0.7
protobuf==3.13.0
psycopg2==2.7.3.2
ptvsd==4.1.3
ptyprocess==0.6.0
pyasn1==0.4.8
pycodestyle==2.5.0
pycparser==2.20
pyflakes==2.1.1
Pygments==2.7.1
PyJWT==1.5.3
pymongo==3.4.0
PyNaCl==1.4.0
pyotp==2.2.7
python-dateutil==2.6.0
python-Levenshtein==0.12.0
python-slugify==1.2.5
pytz==2020.1
PyYAML==5.3.1
regex==2020.7.14
requests==2.21.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rollbar==0.14.7
rsa==4.0
s3transfer==0.2.1
scipy==0.19.1
semver==2.10.2
sh==1.12.14
six==1.15.0
sortedcontainers==2.2.2
SQLAlchemy==1.3.3
swagger-ui-bundle==0.0.3
tenacity==6.2.0
testing.common.database==2.0.3
testing.postgresql==1.3.0
toml==0.10.1
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
unicodecsv==0.14.1
Unidecode==1.1.1
urllib3==1.24.2
vine==1.3.0
virtualenv==20.0.31
voluptuous==0.11.5
wcwidth==0.2.5
Werkzeug==0.16.1
WTForms==2.3.3
zipp==3.1.0
zxcvbn==4.4.28

### How can we reproduce your problem?
Running celery worker with dd-trace, I can see traces on dd console. But after some time I start seeing this warning in logs 

Writer queue is full has more than 1000 traces, some traces will be lost, 586 additional messages skipped
 

### What is the result that you get?
Writer queue is full has more than 1000 traces, some traces will be lost, 586 additional messages skipped

### What is the result that you expected?
I expected all the traces to be sent instead of them to be sent.

**Comment by majorgreys** [comment] 2020-10-22 15:47
@shuklaabhi We have seen this issue crop up before and have been considering how to address it in the tracer. If you can share any details on your celery configuration, that would help us. We are currently working on a change in the tracer that should address the issue of such trace limits #1740.

**Comment by shuklaabhi** [comment] 2020-10-26 15:19
Thanks a lot for replying. I am pasting celery config we are using, its quite simple with RMQ as broker and MongoDB cluster as result backend.

celery.conf.humanize(with_defaults=False, censored=True)

```

ABSOLUTE_LONG_SESSION_TIMEOUT: 1209600
ABSOLUTE_SHORT_SESSION_TIMEOUT: 7200

AWS_ACCESS_KEY_ID: '********'
AWS_SECRET_ACCESS_KEY: '********'
BROKER_HOSTS: ['localhost']
BROKER_PASSWORD: '********'
BROKER_POOL_LIMIT: None
BROKER_TRANSPORT_OPTIONS: {
    'connect_timeout': 1.3,
    'interval_max': 0.0,
    'interval_start': 0.0,
    'interval_step': 0.0,
    'max_retries': 4}
BROKER_USER: 'guest'
BROKER_VHOST: '/'
BROKER_URL: 'amqp://guest:********@localhost:5672/celery'

CANARY_SETTING: 'stage.xeneta.conf.py'
CELERYBEAT_SCHEDULE: {}
CELERYBEAT_SYNC_EVERY: 1
CELERYD_MAX_TASKS_PER_CHILD: 50
CELERYD_PREFETCH_MULTIPLIER: 10
CELERY_ACCEPT_CONTENT: ['json']

CELERY_MONGODB_BACKEND_SETTINGS: {
    'database': '********',
    'host': 'mongodb://**********dev.com,***********dev.com, **********dev.com', ## 3 nodes of a mongo replica
    'options': {   'connectTimeoutMS': 3000,
                   'socketTimeoutMS': 5000,
                   'waitQueueTimeoutMS': 5000},
    'taskmeta_collection': 'taskmeta_reference'}
CELERY_QUEUE: {
 'queue': 'celery'}
CELERY_RESULT_BACKEND: 'mongodb'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_ROUTES: {
    'air.convert_rates': {'queue': 'reports'},
}
CELERY_SEND_TASK_SENT_EVENT: True
CELERY_TASK_ACKS_LATE: True
CELERY_TASK_ALWAYS_EAGER: True
CELERY_TASK_REJECT_ON_WORKER_LOST: True
CELERY_TASK_RESULT_EXPIRES: 86400
CELERY_TASK_SERIALIZER: 'json'
CELERY_TIMEZONE: 'UTC'
CUSTOM_LOG_CONFIG: {
    'disable_existing_loggers': False,
    'formatters': {   'json': {   '()': 'xeneta.common.logging.CustomisedJSONFormatter'}},
    'handlers': {   'development': {   'class': 'logging.StreamHandler',
                                       'formatter': 'json',
                                       'level': 'DEBUG'},
                    'development-quieter': {   'class': 'logging.StreamHandler',
                                               'formatter': 'json',
                                               'level': 'INFO'},
                    'production': {   'class': 'logging.StreamHandler',
                                      'formatter': 'json',
                                      'level': 'INFO'}},
    'loggers': {   '': {   'handlers': ['development'],
                           'level': 'DEBUG',
                           'propagate': False}},
    'version': 1}
DATADOG_AGENT_HOST: 'localhost'
DATADOG_AGENT_PORT: 8126
DATADOG_AGENT_REPORTING: False
DATADOG_API_KEY: '********'
DATADOG_APP_KEY: '********'
DATADOG_ENVIRONMENT: 'development'
DEFAULT_CSV_ENCODING: 'utf-8'
LOG_FORMAT: ('[%(asctime)s][%(levelname)s] %(name)s:%(lineno)d | %(message)s')
LOG_HANDLERS: ['development-quieter']
MONGODB_MAX_WAIT_TIME: 5

crontab: <class 'celery.schedules.crontab'>
load_settings: <function load_settings at 0x103083ea0>
log_config: {
    'disable_existing_loggers': False,
    'formatters': {   'json': {   '()': 'xeneta.common.logging.CustomisedJSONFormatter'}},
    'handlers': {   'development': {   'class': 'logging.StreamHandler',
                                       'formatter': 'json',
                                       'level': 'DEBUG'},
                    'development-quieter': {   'class': 'logging.StreamHandler',
                                               'formatter': 'json',
                                               'level': 'INFO'},
                    'production': {   'class': 'logging.StreamHandler',
                                      'formatter': 'json',
                                      'level': 'INFO'}},
    'loggers': {   '': {   'handlers': ['development-quieter'],
                           'level': 'DEBUG',
                           'propagate': False}},
    'version': 1}


```

**Comment by Kyle-Verhoog** [comment] 2021-07-28 20:52
@shuklaabhi since this issue has been opened we've made some changes to the limits we use in our trace writer. It now goes based off of byte-size of traces (limited by the API to the agent) rather the arbitrary number of 1000. We also have variables that can be used to adjust the limits of the writer (flush interval, max trace size, max payload size). 

You can see the options here: https://ddtrace.readthedocs.io/en/stable/configuration.html

If you're able to update and report back that would be great! I'll close the issue for now but please let us know and we can reopen if the issue is not addressed 🙂

**Closed by Kyle-Verhoog** 2021-07-28 20:52 UTC
Labels: enhancement, integrations
