### ISSUE TITLE
celery 4.1 worker tasks aren't being traced with ddtrace-py 0.11.1

### ISSUE THREAD

**Issue by eedwards-sk** [DataDog/dd-trace-py#451] opened 2018-04-13 18:14 UTC
```
ddtrace==0.11.1
celery==4.1.0
```

I'm manually patching celery due to #423 

I'm getting traces for 'defaultdb' (sqlite), 'redis', and 'postgres' when I run the celery worker

However, I'm not receiving any traces whatsoever for the task runs, and no 'celery' service appears in datadog.

Here's a gist with my worker startup in debug logging mode:
https://gist.github.com/eedwards-sk/f924548c043859901db6918aec95dada

I'm sending traces to a local running agent and I know that's working because I'm seeing the flush records in the logs, and I get traces for the above mentioned services when I'm running it.

(We have another application that is using celery 3.x and their traces show up for tasks, which we instrumented in more or less the same way)

Here's a gist showing how we're instantiating celery and the tracer:
https://gist.github.com/eedwards-sk/fe81f62406e7a245b7c26a9ada19c658

**Comment by palazzem** [comment] 2018-04-16 21:12
Thanks @eedwards-sk ! we're currently working on this problem and will be part of the next release (0.12). Will keep you updated when it's out!

Thanks for reporting the problem

**Comment by palazzem** [comment] 2018-04-18 04:29
Hello again @eedwards-sk ! I'm investigating #423 and I'm wondering if you can provide me more details, so that `ddtrace-run` works as expected in your configuration. If you don't see any error in your logs and everything seems simply "not instrumented", it's possible that Celery core functionalities (i.e. `celery.Celery` or `celery.task`) are imported before calling the `patch(celery=True)`, resulting in a missing instrumentation. They may be imported by the `celery` script (I still need to investigate that part, so consider it a first guess).

For now I would like to tackle one problem at a time, so it would be great if you can share in the other issue (#423) more details. Hopefully, we may fix both problems with a simple patch.

Thank you very much!

**Comment by eedwards-sk** [comment] 2018-04-18 15:49
Hi @palazzem 

The gists I attached when I opened this issue show how I'm running the celery worker, debug output confirming when it's instrumented, and the source code for the entry point which shows instantiation of the tracer and the celery object.

If that wasn't enough detail already, can you please be more specific about what 'more details' you need?

Thanks!

**Comment by eedwards-sk** [comment] 2018-04-30 18:04
Hey @palazzem 

Today we noticed a celery task had been instrumented, but it was a built-in celery task (`celery.backend_cleanup`)

Thus, it appears that at some some aspect of the tracing is working, however our custom tasks are not being instrumented.

Possibly an issue with the datadog tracer and monkeypatching tasks when they are added using `app.autodiscover_tasks()` ?

**Comment by palazzem** [comment] 2018-05-02 08:46
@eedwards-sk I think that it's possible. Actually we found why `ddtrace-run` doesn't work and it will be part of a bugfix release. After writing a PR for the other problem, I would like to triage again this issue because I think it should be really related to the `autodiscover_tasks()`. Also:
* what version of Django are you using? not really relevant but I would like to reproduce the problem with a real app too
* are you using Celery 1.0 style tasks? just asking because we have a known problem for that

**Comment by jallen1788** [comment] 2018-05-02 17:11
I work with @eedwards-sk 

```
>>> django.VERSION
(2, 0, 0, 'final', 0)
```
(but we can upgrade if necessary)

I do not believe we are using Celery 1.0 style tasks. The project is only a few months old.

```
>>> celery.VERSION
version_info_t(major=4, minor=1, micro=0, releaselevel='', serial='')
```

Here is an example of a celery call
```
from celery import shared_task

@shared_task
def foo_bar(baz):
    return 1
```

**Comment by palazzem** [comment] 2018-05-02 20:24
Hello @jallen1788 ! thanks for these details! Definitely not, so I need to check if we're experiencing issues with the `@shared_task` decorator. We're actively working on it right now, and will reach you once we have something stable that you can test (probably next week). Sounds good?

**Comment by eedwards-sk** [comment] 2018-05-02 20:25
@palazzem thanks a bunch, sounds good!

**Comment by palazzem** [comment] 2018-05-29 12:59
@eedwards-sk just an update about the issue. We fixed some issues related to `ddtrace-run` + Celery and how we patch Celery tasks: https://github.com/DataDog/dd-trace-py/pull/469 and https://github.com/DataDog/dd-trace-py/pull/465

They're already on `master` but still not released. We're checking now if there are issues with `@shared_task` decorator so that we can consider this issue closed. Thanks and sorry for waiting more than expected.

**Comment by eedwards-sk** [comment] 2018-05-29 14:44
@palazzem 

Thanks for the update! I'll keep an eye out for 0.12.1 which I assume will have this improvement.

**Comment by palazzem** [comment] 2018-06-12 10:22
Hello @eedwards-sk and @jallen1788! I've reproduced the problem, but would be great if you can confirm it's solved. You should checkout this PR: https://github.com/DataDog/dd-trace-py/pull/486

To use it in your `requirements.txt` just:
```
git+https://github.com/DataDog/dd-trace-py@palazzem/django-shared-tasks
```

You can instrument your Celery worker, directly via `ddtrace-run` script. Now both Django and Celery should be properly instrumented with our entrypoint script. If you confirm that, I'll ship a new release tomorrow that should address entirely the Celery problem.

**Comment by palazzem** [comment] 2018-06-12 10:29
@eedwards-sk @jallen1788 oh I forgot to write that if you test it locally, remember to disable the Django Debug Mode, otherwise the Tracer is disabled and no traces are sent to the Agent. It means having the `DEBUG = False` flag.

**Comment by palazzem** [comment] 2018-06-12 14:08
I'm closing this issue because it should be solved (and I'm preparing the 0.12.1 release). In the meantime you can still test it in your system via:
```
# requirements.txt
git+https://github.com/DataDog/dd-trace-py  # points to our master that includes the fix
```
I'll reach you out once the release is out!

**Closed** 2018-06-12 14:09 UTC
Labels: bug, integrations

**Comment by eedwards-sk** [comment] 2018-06-15 15:09
@palazzem IT WORKS!! :D

Thank you!

**Comment by eedwards-sk** [comment] 2019-08-01 16:23
We may need to re-open this for 0.26.0+ which is failing to auto-instrument celery tasks through `ddtrace-run` again.

**Comment by eedwards-sk** [comment] 2019-08-01 16:50
I confirmed it's patching celery with debug trace logs, but not tracing the tasks themselves.

```
2019-08-01 16:32:12,459 INFO [ddtrace.monkey] [monkey.py:140] - patched 8/30 modules (botocore,celery,django,flask,psycopg,redis,requests,sqlite3)
```
