### ISSUE TITLE
Memory leak after "Failed to send traces to Datadog Agent"

### ISSUE THREAD

**Issue by atainter** [DataDog/dd-trace-py#1484] opened 2020-06-04 20:41 UTC
Hey, I wanted to reach out because I started seeing a memory leak in my application after upgrading from version 0.29.0 -> 0.37.1.

<img width="2202" alt="Screen Shot 2020-06-04 at 1 38 07 PM" src="https://user-images.githubusercontent.com/7866859/83808023-db0b9380-a668-11ea-9ecd-be4f3363940c.png">

I've seen the memory happen 7 different times in our production cluster. After looking at the logs, it seems like they always have the same two errors right before the memory leak starts: 

```
Failed to send traces to Datadog Agent at http://datadog-agent.infra:8126: [Errno 111] Connection refused
Failed to send traces to Datadog Agent at http://datadog-agent.infra:8126: [Errno -2] Name or service not known
```

The memory leak happens on a new service that is currently only taking healthcheck traffic, so I doubt that it's something wrong with our code. I've already profiled this locally and can't reproduce.

Can someone help investigate? Thanks

**Comment by majorgreys** [comment] 2020-06-05 00:14
@atainter, can you open a support ticket (https://www.datadoghq.com/support/) for this? We will need to get more details on your environment as it's a difficult issue to reproduce.

**Comment by ginni-gidwani** [comment] 2020-08-10 08:57
@atainter Did you get any updates one this? We are facing the same issue and not able to integrate because of it.

**Comment by atainter** [comment] 2020-08-10 16:30
@ginni-gidwani  No, we're still seeing transient memory leaks. I added some memory profiling code to another environment, but I haven't found anything yet. I'll post updates in this thread.

**Comment by atainter** [comment] 2020-09-04 17:00
@ginni-gidwani I finally managed to track down the source of the memory leak. Looks like an issue with integration between ddtrace and a third party library we're using to track exceptions (sentry-sdk==0.10.0). Here's the full traceback with tracemalloc:

```
1 Traceback: (memory blocks=10499) (size=1722.0625 )
  File "/usr/local/lib/python3.7/threading.py", line 890
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/_worker.py", line 69
    self.run_periodic()
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/writer.py", line 232
    self.flush_queue()
  File "/usr/local/lib/python3.7/site-packages/ddtrace/internal/writer.py", line 175
    traces_responses = self.api.send_traces(traces)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/api.py", line 234
    responses.append(self._flush(payload))
  File "/usr/local/lib/python3.7/site-packages/ddtrace/api.py", line 242
    response = self._put(self._traces, payload.get_payload(), payload.length)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/api.py", line 276
    resp = get_connection_response(conn)
  File "/usr/local/lib/python3.7/site-packages/ddtrace/compat.py", line 185
    return conn.getresponse()
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/stdlib.py", line 91
    rv = real_getresponse(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/http/client.py", line 1340
    response = self.response_class(self.sock, method=self._method)
  File "/usr/local/lib/python3.7/http/client.py", line 244
    self.fp = sock.makefile("rb")
```

Going to investigate more to see how I can fix the issue.

**Comment by atainter** [comment] 2020-11-04 22:35
@jamiepenney , yes! It was actually caused by an issue with an old version of the Sentry SDK. Sentry was catching exceptions from the ddtrace SDK and causing a memory leak in the stdlib integration. Upgrading Sentry worked for us. 

I used tracemalloc to locate the source of the leak.
https://tech.buzzfeed.com/finding-and-fixing-memory-leaks-in-python-413ce4266e7d

**Comment by jamiepenney** [comment] 2020-11-04 22:46
Great, thanks. We've had issues getting tracemalloc running in our environment but other python memory profilers show a growth of 1MB per minute in python objects on our background jobs processor. Will keep investigating, thanks for your help!

**Comment by Kyle-Verhoog** [comment] 2021-07-29 03:38
Going to close this as it looks like `ddtrace` wasn't primarily responsible.

@jamiepenney please re-open if you believe that `ddtrace` is responsible!

**Closed by Kyle-Verhoog** 2021-07-29 03:38 UTC
