### ISSUE TITLE
DD_TAGS support

### ISSUE THREAD

**Issue by inikolaev** [DataDog/dd-trace-py#3758] opened 2022-05-25 09:36 UTC
It looks like `DD_TAGS` is not consistently used across the library and there are still parts that use `DATADOG_TAGS`, e.g. [here](https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/vendor/dogstatsd/base.py#L190).

Is that by design or just some legacy leftovers?

**Comment by brettlangdon** [comment] 2022-05-25 12:03
hey @inikolaev I also saw your message in our public Slack about how this relates to tags being added to metrics.

Which metrics are you interested in seeing these additional tags added to? Specific built-in APM Tracing metrics, or custom metrics you are emitting from your application?

There is a chance this is a duplicate of https://github.com/DataDog/datadogpy/issues/702, but depends on your usage/expected outcome.

**Comment by brettlangdon** [comment] 2022-05-25 17:06
We talked a bit in Slack.

@inikolaev was looking how to add more tags to the automatically generated `trace.<operation_name>.*` metrics that we generate from Spans to drive some features in the UI.

Unfortunately we currently do not support adding additional arbitrary tags to these metrics. The primary reason for this is because a lot of Span data is high cardinality and can cause issues with those specific metrics.

Instead, it is suggested to [generate custom metrics from spans](https://docs.datadoghq.com/tracing/generate_metrics/) to query and analyze Span from the [trace explorer](https://docs.datadoghq.com/tracing/trace_explorer/).

**Closed by brettlangdon** 2022-05-25 17:06 UTC
