### ISSUE TITLE
1.19.0rc1 tox won't be able to stop. process.commute() never return. 

### ISSUE THREAD

**Issue by qiaouchicago** [DataDog/dd-trace-py#6894] opened 2023-09-12 19:43 UTC
### Summary of problem
When running tox test with this version, the subprocess never returns. 

1.18.5 and 1.18.4 does not have this problem. 
### Which version of dd-trace-py are you using?
1.19.0rc1
### Which version of pip are you using?
 21.3.1 

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

### What is the result that you get?
pytest finish but tox stuck
### What is the result that you expected?
tox should finish .

**Comment by romainkomorndatadog** [comment] 2023-09-14 08:00
@qiaouchicago , we need more details on how to reproduce the issue you're reporting.

I just tried testing [Flask](https://github.com/pallets/flask) using `tox` in a virtual Python `3.11` environment with `ddtrace==1.19.0rc1` installed and didn't encounter any hangs:
```
(ddtrace-1.19rc01-tox-flask) romain.komorn@COMP-CLXFH7L2J3 flask-nonshallow % tox run
py312: skipped because could not find python interpreter with spec(s): py312
py312: SKIP ⚠ in 0.55 seconds
...
The HTML pages are in .tox/tmp/docs/html.
.pkg: _exit> python /Users/romain.komorn/.pyenv/versions/3.11.0/envs/ddtrace-1.19rc01-tox-flask/lib/python3.11/site-packages/pyproject_api/_backend.py True flit_core.buildapi
  py312: SKIP (0.55 seconds)
  py311: OK (2.46=setup[0.39]+cmd[2.07] seconds)
  py310: OK (11.95=setup[7.09]+cmd[4.86] seconds)
  py39: OK (11.94=setup[6.98]+cmd[4.96] seconds)
  py38: OK (12.61=setup[7.32]+cmd[5.29] seconds)
  pypy310: SKIP (0.00 seconds)
  py311-min: OK (8.55=setup[5.18]+cmd[3.38] seconds)
  py38-dev: FAIL code 1 (23.48=setup[16.42]+cmd[7.06] seconds)
  style: FAIL code 1 (22.14=setup[1.75]+cmd[20.39] seconds)
  typing: OK (13.55=setup[4.58]+cmd[8.97] seconds)
  docs: OK (13.08=setup[6.07]+cmd[7.01] seconds)
  evaluation failed :( (120.34 seconds)
```
And we I see results in my CI tests view for this project and my branch:
![image](https://github.com/DataDog/dd-trace-py/assets/136473744/7c6842c3-00aa-4372-acce-f29c4c09dd07)

Here's what my `pip freeze` looks like, for reference:
```
(ddtrace-1.19rc01-tox-flask) romain.komorn@COMP-CLXFH7L2J3 flask-nonshallow % pip freeze
asgiref==3.7.2
attrs==23.1.0
blinker==1.6.2
bytecode==0.15.0
cachetools==5.3.1
cattrs==23.1.2
chardet==5.2.0
click==8.1.7
colorama==0.4.6
ddsketch==2.0.4
ddtrace==1.19.0rc1
Deprecated==1.2.14
distlib==0.3.7
envier==0.4.0
filelock==3.12.4
-e git+ssh://git@github.com/romainkomorndatadog/flask.git@a0445219ea344777264ef88286973cd344d926df#egg=Flask
importlib-metadata==6.8.0
iniconfig==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
opentelemetry-api==1.20.0
packaging==23.1
platformdirs==3.10.0
pluggy==1.3.0
protobuf==4.24.3
pyproject-api==1.6.1
pytest==7.4.0
python-dotenv==1.0.0
six==1.16.0
tox==4.11.3
typing_extensions==4.7.1
virtualenv==20.24.5
Werkzeug==2.3.7
wrapt==1.15.0
xmltodict==0.13.0
zipp==3.16.2
```

And here are my local edits to add `ddtrace` `1.19.0rc1` to `tox` in the repo:
```
(ddtrace-1.19rc01-tox-flask) romain.komorn@COMP-CLXFH7L2J3 flask-nonshallow % git diff
diff --git a/requirements/tests.txt b/requirements/tests.txt
index d8fedc4a..91287b94 100644
--- a/requirements/tests.txt
+++ b/requirements/tests.txt
@@ -17,3 +17,5 @@ pytest==7.4.0
     # via -r requirements/tests.in
 python-dotenv==1.0.0
     # via -r requirements/tests.in
+ddtrace==1.19.0rc1
+    # via me
diff --git a/tox.ini b/tox.ini
index cb735d28..9f93b96c 100644
--- a/tox.ini
+++ b/tox.ini
@@ -25,8 +25,8 @@ deps =
     dev: https://github.com/pallets/click/archive/refs/heads/main.tar.gz
 #    examples/tutorial[test]
 #    examples/javascript[test]
-# commands = pytest -v --tb=short --basetemp={envtmpdir} {posargs:tests examples}
-commands = pytest -v --tb=short --basetemp={envtmpdir} {posargs:tests}
+# commands = pytest --ddtrace -v --tb=short --basetemp={envtmpdir} {posargs:tests examples}
+commands = pytest --ddtrace -v --tb=short --basetemp={envtmpdir} {posargs:tests}
```

**Comment by romainkomorndatadog** [comment] 2023-09-14 08:14
Out of curiosity, I also tried with `ddtrace-run tox run` instead of adding `--ddtrace` as an argument to the `pytest` command, but that also did not produce a hang of any sort:
```
(ddtrace-1.19rc01-tox-flask) romain.komorn@COMP-CLXFH7L2J3 flask-nonshallow % ddtrace-run tox run
py312: skipped because could not find python interpreter with spec(s): py312
py312: SKIP ⚠ in 0.01 seconds
...
.pkg: _exit> python /Users/romain.komorn/.pyenv/versions/3.11.0/envs/ddtrace-1.19rc01-tox-flask/lib/python3.11/site-packages/pyproject_api/_backend.py True flit_core.buildapi
  py312: SKIP (0.01 seconds)
  py311: OK (1.49=setup[0.40]+cmd[1.09] seconds)
  py310: OK (1.52=setup[0.28]+cmd[1.24] seconds)
  py39: OK (1.52=setup[0.28]+cmd[1.24] seconds)
  py38: OK (1.56=setup[0.28]+cmd[1.28] seconds)
  pypy310: SKIP (0.00 seconds)
  py311-min: OK (1.37=setup[0.28]+cmd[1.08] seconds)
  py38-dev: FAIL code 1 (5.01=setup[0.28]+cmd[4.73] seconds)
  style: FAIL code 1 (1.22=setup[0.00]+cmd[1.22] seconds)
  typing: OK (0.54=setup[0.30]+cmd[0.24] seconds)
  docs: OK (6.35=setup[0.33]+cmd[6.02] seconds)
  evaluation failed :( (20.63 seconds)
```

**Comment by qiaouchicago** [comment] 2023-09-14 12:38
Sorry, our tests involves internal packages and I do not think you can reproduce the exact tests without them.

**Comment by lawrenceong** [comment] 2023-10-04 03:24
I can confirm that something similar is happening to us as well.  We upgraded ddtrace from 1.18.5 to 1.20.2.  The app is running on flask with gevent and it just won't exit cleanly.  We have to send a second TERM signal to terminate it.

Can confirm that the issue is present in 1.19.0.
Can confirm that the issue is not present in 1.18.6

**Comment by lawrenceong** [comment] 2023-10-04 04:08
Logs from a throw stack on exit that may help
```
Logs from the stack
```
 Traceback (most recent call last):
  File ".../python3.10/site-packages/ddtrace/internal/atexit.py", line 67, in handle_exit
    f()
  File ".../python3.10/site-packages/ddtrace/tracer.py", line 314, in _atexit
    self.shutdown(timeout=self.SHUTDOWN_TIMEOUT)
  File ".../python3.10/site-packages/ddtrace/tracer.py", line 1048, in shutdown
    forksafe.unregister(self._child_after_fork)
  File ".../python3.10/site-packages/ddtrace/internal/forksafe.py", line 56, in unregister
    _registry.remove(after_in_child)
ValueError: list.remove(x): x not in list 
```

**Comment by lawrenceong** [comment] 2023-10-06 06:57
@romainkomorndatadog Not directly related to tox.  Issue is related as the running app cannot exit cleanly and is due to update to version 1.19.x

**Comment by romainkomorndatadog** [comment] 2023-10-06 09:24
@lawrenceong , great, that'd be very helpful. @emmettbutler , can I shuffle this over to you for proper routing, since it's not a CI / pytest integration issue?

**Comment by lawrenceong** [comment] 2023-10-18 03:03
Raised #7273 for the simple test

**Comment by romainkomorndatadog** [comment] 2023-10-18 07:50
I'm going to close this in favor of #7273 .

**Closed by romainkomorndatadog** 2023-10-18 07:50 UTC

**Comment by qiaouchicago** [comment] 2023-11-13 19:59
This problem is happening again in 2.1.6
