### ISSUE TITLE
gunicorn + flask generating socket.error traces for every request

### ISSUE THREAD

**Issue by eedwards-sk** [DataDog/dd-trace-py#453] opened 2018-04-18 20:45 UTC
This stack trace has shown up before for gunicorn for other users in somewhat seemingly similar situations, but no clarity on a reason why or a solution:
https://github.com/benoitc/gunicorn/issues?q=is%3Aissue+resource+unavailable+is%3Aclosed

Not sure if related to those issues or not, I wasn't able to verify.

In our datadog 'span metadata' for `flask.request` traces, we're seeing the following `socket.error` stack trace, even though the request was not an error/exception (a successful 200, in fact):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable
```

This is with gunicorn 19.7.1 and ddtrace-py 0.11.1

**Comment by palazzem** [comment] 2018-04-19 15:10
Hello @eedwards-sk! If our tracing system detects an exception, it will be added in the request span. What is important is:
* the issue is not caused by our tracer (and I think it should not)
* even if we add the stack trace to the request span, the trace must not be flagged as an Error in our backend because, in the end, it was a 200

What is the expected behavior you're looking for? And how many times does it happen in your environment?

Thanks!

**Comment by eedwards-sk** [comment] 2018-04-19 15:40
Hi @palazzem 

Thank you for the response. This is happening on all of our flask.request traces for a gunicorn app.

From this thread https://github.com/benoitc/gunicorn/issues/514 where the same stack trace is reported (albeit it's fairly generic so this could be unrelated), someone mentions this which sounds plausible:

>If it helps, I found that our code was logging an exception when it should have been logging an error. If I remember correctly, there is one global variable in python that holds the last stack trace. Since gunicorn polls the socket over and over and catches this Errno 11 exception every time, this is the stack trace you will see if you print a stack trace when an exception hasn't actually been raised.

**Comment by palazzem** [comment] 2018-04-19 16:51
OK it makes sense, let me double check and reproduce the problem because of course is misleading if the tracer catches an exception that is already handled (or it will be handled) by Gunicorn resulting in a 200 response.

**Comment by squarelover** [comment] 2019-01-04 20:44
Any update on this bug? I'm having the same issue. Is there a workaround?

**Comment by eedwards-sk** [comment] 2019-01-04 21:31
@squarelover what version are you on? We saw this problem go away once we updated to a newer version (currently on 0.17.1)

**Comment by irabinovitch** [comment] 2019-03-30 01:55
@squarelover did updating to 0.17.x help?

**Comment by brettlangdon** [comment] 2019-06-07 13:56
Closing this issue, @squarelover please feel free to re-open if you are still experiencing this issue.

**Closed by brettlangdon** 2019-06-07 13:56 UTC
Labels: bug
