### ISSUE TITLE
Gunicorn with gevent workers

### ISSUE THREAD

**Issue by danieluisilva** [DataDog/dd-trace-py#230] opened 2017-03-23 10:50 UTC
Hi, i use gunicorn with gevent workers, after install ddtrace i'm not receiving db traces, if switch for sync workers i receive all db traces.
I tried on gunicorn post_fork patch gevent but not work anyway. 
This is a possible bug or missing something?

My system is:
ddtrace==0.6.0
Django==1.10.6
gevent==1.2.1
gunicorn==19.6.0

**Comment by underyx** [comment] 2017-03-23 10:53
We use gunicorn + gevent + bottle and everything works perfectly. Maybe look further into it @danieluisilva

**Comment by danieluisilva** [comment] 2017-03-23 11:03
ty @underyx , u patch gevent where?

**Comment by underyx** [comment] 2017-03-23 11:21
We do patching on the very first lines of our package's `__init__.py`, like this:

```python
import ddtrace
ddtrace.patch_all()
ddtrace.patch(gevent=True)

from gevent import monkey
monkey.patch_all()
```

…maybe you're missing `ddtrace.patch(gevent=True)`? We found that `ddtrace.patch_all` doesn't cover gevent.

**Comment by danieluisilva** [comment] 2017-03-23 12:16
I have done this before without success. 

The gunicorn does the monkey.patch_all() on worker. I don't import gevent in my code.

I tried ddtrace.patch(gevent=True) on my code and in gunicorn post_fork.

**Comment by underyx** [comment] 2017-04-06 15:23
So @danieluisilva isn't the problem that gunicorn runs `gevent.monkey.patch_all()` before you call `ddtrace.patch(gevent=True)`? Try manually calling `gevent.monkey.patch_all()`, like I'm doing.

**Comment by palazzem** [comment] 2017-05-26 12:23
Hello @danieluisilva and @underyx! do we have an update for this issue? While we're working to improve the `gevent` integration (i.e. another required change https://github.com/DataDog/dd-trace-py/issues/275), I'm wondering if there are other issues while using `gunicorn`.

Thank you!

**Comment by danieluisilva** [comment] 2017-05-27 10:43
Hey,i don't have any update.
I can't figure the source of problem. I tried ddtrace.patch(gevent=True) on my code but doesn't work.. 

I think the problem is related with the gunicorn workers, if the workers type are **sync** the trace work  as supposed. But it the type is set to **gevent** the trace wont show me nothing.

One more thing i don't use gevent directly in my code.

**Comment by palazzem** [comment] 2017-05-29 11:36
Thanks for the update @danieluisilva! We will keep this issue opened so that we can proceed to investigate on that. Will keep you updated!

**Comment by underyx** [comment] 2017-05-29 11:45
@danieluisilva so, again, could you please try `ddtrace.patch(gevent=True)` and *after that* manually running `monkey.patch_all()`? What I think is happening to you is:

1. you run `gunicorn` with `gevent` workers
2. when starting, `gunicorn` runs `gevent.monkey.patch_all()` for you
3. `gunicorn` imports your code and your code patches `gevent` with `ddtrace.patch(gevent=True)`

Notice how step 2 and step 3 are in the wrong order here. Tracing is added to `gevent` *after* gevent is monkeypatched into your standard library. This is why I'm suggesting that as step 4 you should yourself run `gevent.monkey.patch_all()`, since at that point `gevent` will have tracing added to it.

**Comment by danieluisilva** [comment] 2017-05-29 14:15
@underyx as i had said, i already tried this..

> from ddtrace import patch_all, patch
> from gevent import monkey
> patch_all()
> patch(gevent=True)
> monkey.patch_all()

But this not work..

**Comment by underyx** [comment] 2017-05-29 14:32
Right, sorry, I misunderstood your comment then.

Anyway, that might not be supposed to be working still, since you're
importing `gevent.monkey` before it's monkeypatched. On line 5 `monkey`
refers to what was imported on line 2, which is the original gevent. Can
you try importing after `patch(gevent=True)`?

**Comment by ericcchamberlain** [comment] 2017-11-16 23:15
I am also experiencing this issue. Were you able to resolve it?

**Comment by yograterol** [comment] 2018-03-13 16:44
I am having the same issue with Gevent + Django + Gunicorn.

The WSGI app doesn't start when we use dd-trace to start a gunicorn instance with Gevent as worker class. 

We tried patching the wsgi file but it didn't work.

**Comment by palazzem** [comment] 2018-03-13 16:56
Hello @yograterol . Can you give some details about used versions for each library? Also this doesn't work at all, or only when using `ddtrace-run` script? Can you provide a snippet of the patched wsgi file (so I guess you added some of our code in that initializer, right?).

Thank you very much!

**Comment by ericcchamberlain** [comment] 2018-03-13 17:16
We ended up discovering two issues with DataDog's agent:

1) the DD agent did not properly work with Gevent in non-trivial applications (their support team acknowledged this and asked us to change our application to use prefork instead of fixing the issue) 

2) the DD agent was not picking up exceptions from custom error handlers in Django. 

We invested about 40 hours into debugging their product and had to send them example projects where their agent was not working in order to get any assistance. Their support was awful, uninformed, and unwilling to investigate anything other than common error scenarios. After providing proof, they acknowledged the issues and then asked us to rank how important it was to us to fix and properly support them.

As a result, we ended up going with New Relic, and we have been very happy with our decision. I recommend you save yourself the headache and do the same.

**Comment by palazzem** [comment] 2018-03-22 08:40
Hello @ericcchamberlain. We apologize for the delay and understand your frustration. We're working to improve the process, and have made tangible improvements recently. That said, we understand we still have work to do in this regard.

About this specific issue, we're interested on finding a solution especially because we want to support properly `gevent` run via `gunicorn`. An engineer from my team will work on it in the next couple of weeks. Having more details from @yograterol would be great, just because we would like to know the current latest state of the issue.

**Comment by palazzem** [comment] 2018-03-28 13:29
We made some progress on this issue and this PR is out. It should address the original problem:
> Hi, i use gunicorn with gevent workers, after install ddtrace i'm not receiving db traces, if switch for sync workers i receive all db traces.

Reference: https://github.com/DataDog/dd-trace-py/pull/442 (under review)
Would be great if who's in this thread with the original problem can test it. Thank you very much and sorry for the delay.

**Comment by palazzem** [comment] 2018-03-29 15:05
PR #442 reproduced the original issue. It has been merged and will be part of the next bugfix release (0.11.1) so I'm going to close this issue. The ETA is next week, and it should close connected problems. If it doesn't solve entirely the problem (or if new problems are found), feel free to submit the issue again!

Thank you very much!

**Closed by palazzem** 2018-03-29 15:05 UTC
Labels: bug, integrations
